In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("Data/2018drives_augmented.tsv", sep="\t", index_col=False)
df

,offense,defense,game_id,plays,start_yardline,yards,end_yardline,drive_result,points,start_distance,dist_range
0,Alabama,Louisville,401012246,7,35,65,100,TD,7,65,"(60.0, 65.0]"
1,Louisville,Alabama,401012246,4,75,20,55,PUNT,0,75,"(70.0, 75.0]"
2,Alabama,Louisville,401012246,8,20,63,65,FUMBLE,0,80,"(75.0, 80.0]"
3,Louisville,Alabama,401012246,3,83,-1,84,PUNT,0,83,"(80.0, 85.0]"
4,Alabama,Louisville,401012246,6,45,55,100,TD,7,55,"(50.0, 55.0]"
5,Louisville,Alabama,401012246,8,75,49,26,INT,0,75,"(70.0, 75.0]"
6,Alabama,Louisville,401012246,6,25,75,100,TD,7,75,"(70.0, 75.0]"
7,Louisville,Alabama,401012246,6,86,31,55,PUNT,0,86,"(85.0, 90.0]"
8,Alabama,Louisville,401012246,5,22,19,41,PUNT,0,78,"(75.0, 80.0]"
9,Louisville,Alabama,401012246,4,80,20,60,PUNT,0,80,"(75.0, 80.0]"
10,Alabama,Louisville,401012246,6,20,33,53,PUNT,0,80,"(75.0, 80.0]"
11,Louisville,Alabama,401012246,3,85,-6,91,PUNT,0,85,"(80.0, 85.0]"
12,Alabama,Louisville,401012246,3,75,25,100,TD,7,25,"(20.0, 25.0]"
13,Louisville,Alabama,401012246,6,75,10,65,PUNT,0,75,"(70.0, 75.0]"
14,Alabama,Louisville,401012246,4,37,63,100,TD,7,63,"(60.0, 65.0]"
15,Louisville,Alabama,401012246,10,96,75,3,TD,7,96,"(95.0, 100.0]"
16,Louisville,Alabama,401012246,3,76,-4,80,PUNT,0,76,"(75.0, 80.0]"
17,Alabama,Louisville,401012246,6,42,37,79,FG,3,58,"(55.0, 60.0]"
18,Louisville,Alabama,401012246,6,94,26,68,PUNT,0,94,"(90.0, 95.0]"
19,Alabama,Louisville,401012246,13,21,70,91,MISSED FG,0,79,"(75.0, 80.0]"
20,Louisville,Alabama,401012246,1,80,0,80,INT TD,-7,80,"(75.0, 80.0]"
21,Louisville,Alabama,401012246,5,37,32,5,DOWNS,0,37,"(35.0, 40.0]"
22,Alabama,Louisville,401012246,3,5,9,14,PUNT,0,95,"(90.0, 95.0]"
23,Louisville,Alabama,401012246,5,52,52,0,TD,7,52,"(50.0, 55.0]"
24,Washington,Auburn,401012248,3,75,0,75,PUNT,0,75,"(70.0, 75.0]"
25,Auburn,Washington,401012248,6,64,36,100,TD,7,36,"(35.0, 40.0]"
26,Washington,Auburn,401012248,6,75,22,53,INT,0,75,"(70.0, 75.0]"
27,Auburn,Washington,401012248,11,37,49,86,FG,3,63,"(60.0, 65.0]"
28,Washington,Auburn,401012248,7,75,61,14,FG,3,75,"(70.0, 75.0]"
29,Auburn,Washington,401012248,8,24,61,85,MISSED FG,0,76,"(75.0, 80.0]"
...,...,...,...,...,...,...,...,...,...,...,...
9631,Hawai'i,Nevada,401022542,4,8,9,17,PUNT,0,92,"(90.0, 95.0]"
9632,Nevada,Hawai'i,401022542,4,40,18,22,FUMBLE,0,40,"(35.0, 40.0]"
9633,Hawai'i,Nevada,401022542,8,25,30,55,PUNT,0,75,"(70.0, 75.0]"
9634,Nevada,Hawai'i,401022542,8,80,80,0,TD,7,80,"(75.0, 80.0]"
9635,Hawai'i,Nevada,401022542,10,25,72,97,DOWNS,0,75,"(70.0, 75.0]"
9636,Nevada,Hawai'i,401022542,6,97,58,39,MISSED FG,0,97,"(95.0, 100.0]"
9637,Hawai'i,Nevada,401022542,3,39,0,39,PUNT,0,61,"(60.0, 65.0]"
9638,Hawai'i,Nevada,401022542,4,82,-1,81,DOWNS,0,18,"(15.0, 20.0]"
9639,Nevada,Hawai'i,401022542,9,81,81,0,TD,7,81,"(80.0, 85.0]"
9640,Hawai'i,Nevada,401022542,4,25,6,31,DOWNS,0,75,"(70.0, 75.0]"
9641,Nevada,Hawai'i,401022542,4,31,-4,35,PUNT,0,31,"(30.0, 35.0]"
9642,Hawai'i,Nevada,401022542,9,20,80,100,TD,7,80,"(75.0, 80.0]"
9643,Nevada,Hawai'i,401022542,4,24,24,0,TD,7,24,"(20.0, 25.0]"
9644,San Diego State,San José State,401022543,5,25,2,27,PUNT,0,75,"(70.0, 75.0]"
9645,San José State,San Diego State,401022543,12,77,52,25,FG,3,77,"(75.0, 80.0]"
9646,San Diego State,San José State,401022543,1,35,0,35,FUMBLE,0,65,"(60.0, 65.0]"
9647,San José State,San Diego State,401022543,8,35,28,7,FG,3,35,"(30.0, 35.0]"
9648,San Diego State,San José State,401022543,17,25,75,100,TD,7,75,"(70.0, 75.0]"
9649,San José State,San Diego State,401022543,6,89,45,44,PUNT,0,89,"(85.0, 90.0]"
9650,San Diego State,San José State,401022543,3,12,9,21,PUNT,0,88,"(85.0, 90.0]"
9651,San José State,San Diego State,401022543,3,71,5,66,PUNT,0,71,"(70.0, 75.0]"
9652,San Diego State,San José State,401022543,13,7,74,81,FG,3,93,"(90.0, 95.0]"
9653,San José State,San Diego State,401022543,7,75,35,40,PUNT,0,75,"(70.0, 75.0]"
9654,San Diego State,San José State,401022543,10,10,85,95,FG,3,90,"(85.0, 90.0]"
9655,San José State,San Diego State,401022543,14,65,65,0,TD,7,65,"(60.0, 65.0]"
9656,San Diego State,San José State,401022543,5,25,33,58,PUNT,0,75,"(70.0, 75.0]"
9657,San José State,San Diego State,401022543,10,91,46,45,INT,0,91,"(90.0, 95.0]"
9658,San Diego State,San José State,401022543,4,65,1,66,FG,3,35,"(30.0, 35.0]"
9659,San José State,San Diego State,401022543,9,75,39,36,DOWNS,0,75,"(70.0, 75.0]"
9660,San Diego State,San José State,401022543,3,36,8,44,PUNT,0,64,"(60.0, 65.0]"

In [2]:
grouped_df = pd.read_csv("Data/2018drives_grouped.tsv", sep="\t", index_col=False)
grouped_df

    start_distance  count      mean
0                1      3  2.333333
1                2      4  6.000000
2                3     13  5.615385
3                4      6  5.000000
4                5      2  7.000000
5                6      6  5.833333
6                7     12  5.333333
7                8      7  4.285714
8                9     11  5.272727
9               10      9  5.000000
10              11     10  4.800000
11              12      7  6.000000
12              13     12  4.250000
13              14     10  4.300000
14              15     10  5.800000
15              16      4  5.250000
16              17      8  5.250000
17              18     12  3.666667
18              19      9  4.111111
19              20     10  4.800000
20              21     16  5.187500
21              22     16  3.937500
22              23     20  4.200000
23              24     11  2.818182
24              25     62  4.193548
25              26     14  4.214286
26              27     21  5.238095
27              28     19  3.368421
28              29     11  3.000000
29              30     17  5.235294
..             ...    ...       ...
70              71    168  2.238095
71              72    171  1.760234
72              73    174  1.735632
73              74    190  2.542105
74              75   2433  1.709412
75              76    186  1.811828
76              77    182  1.785714
77              78    189  1.640212
78              79    177  1.887006
79              80    594  1.792929
80              81    127  2.275591
81              82    151  1.655629
82              83    139  1.187050
83              84    128  1.445312
84              85    167  1.532934
85              86    105  2.123810
86              87    115  1.730435
87              88    125  1.536000
88              89    106  0.924528
89              90    136  1.264706
90              91     80  0.550000
91              92    101  1.504950
92              93     67  1.000000
93              94     69  1.304348
94              95     64  1.437500
95              96     54  1.166667
96              97     56  0.500000
97              98     61  1.229508
98              99     67  0.955224
99             100      2  3.500000

[100 rows x 3 columns]

In [3]:
from sklearn.linear_model import LinearRegression

x = np.array(grouped_df["start_distance"]).reshape(-1, 1)
y = np.array(grouped_df["mean"]).reshape(-1, 1)
weights = np.array(grouped_df["count"])

reg = LinearRegression().fit(x, y, sample_weight=weights)
print(reg.score(x, y, sample_weight=weights))
print()
print(reg.coef_)
print(reg.intercept_)

0.8056954578118931

[[-0.04590342]]
[5.35287406]

In [4]:
df = df[["offense", "defense", "game_id", "start_distance", "points"]].copy()
df["expectedPoints"] = reg.predict(np.array(df["start_distance"]).reshape(-1, 1))
df

,offense,defense,game_id,start_distance,points,expectedPoints
0,Alabama,Louisville,401012246,65,7,2.369152
1,Louisville,Alabama,401012246,75,0,1.910118
2,Alabama,Louisville,401012246,80,0,1.680601
3,Louisville,Alabama,401012246,83,0,1.542891
4,Alabama,Louisville,401012246,55,7,2.828186
5,Louisville,Alabama,401012246,75,0,1.910118
6,Alabama,Louisville,401012246,75,7,1.910118
7,Louisville,Alabama,401012246,86,0,1.405180
8,Alabama,Louisville,401012246,78,0,1.772408
9,Louisville,Alabama,401012246,80,0,1.680601
10,Alabama,Louisville,401012246,80,0,1.680601
11,Louisville,Alabama,401012246,85,0,1.451084
12,Alabama,Louisville,401012246,25,7,4.205289
13,Louisville,Alabama,401012246,75,0,1.910118
14,Alabama,Louisville,401012246,63,7,2.460959
15,Louisville,Alabama,401012246,96,7,0.946146
16,Louisville,Alabama,401012246,76,0,1.864214
17,Alabama,Louisville,401012246,58,3,2.690476
18,Louisville,Alabama,401012246,94,0,1.037953
19,Alabama,Louisville,401012246,79,0,1.726504
20,Louisville,Alabama,401012246,80,-7,1.680601
21,Louisville,Alabama,401012246,37,0,3.654448
22,Alabama,Louisville,401012246,95,0,0.992050
23,Louisville,Alabama,401012246,52,7,2.965896
24,Washington,Auburn,401012248,75,0,1.910118
25,Auburn,Washington,401012248,36,7,3.700351
26,Washington,Auburn,401012248,75,0,1.910118
27,Auburn,Washington,401012248,63,3,2.460959
28,Washington,Auburn,401012248,75,3,1.910118
29,Auburn,Washington,401012248,76,0,1.864214
...,...,...,...,...,...,...
9631,Hawai'i,Nevada,401022542,92,0,1.129760
9632,Nevada,Hawai'i,401022542,40,0,3.516737
9633,Hawai'i,Nevada,401022542,75,0,1.910118
9634,Nevada,Hawai'i,401022542,80,7,1.680601
9635,Hawai'i,Nevada,401022542,75,0,1.910118
9636,Nevada,Hawai'i,401022542,97,0,0.900243
9637,Hawai'i,Nevada,401022542,61,0,2.552766
9638,Hawai'i,Nevada,401022542,18,0,4.526613
9639,Nevada,Hawai'i,401022542,81,7,1.634697
9640,Hawai'i,Nevada,401022542,75,0,1.910118
9641,Nevada,Hawai'i,401022542,31,0,3.929868
9642,Hawai'i,Nevada,401022542,80,7,1.680601
9643,Nevada,Hawai'i,401022542,24,7,4.251192
9644,San Diego State,San José State,401022543,75,0,1.910118
9645,San José State,San Diego State,401022543,77,3,1.818311
9646,San Diego State,San José State,401022543,65,0,2.369152
9647,San José State,San Diego State,401022543,35,3,3.746255
9648,San Diego State,San José State,401022543,75,7,1.910118
9649,San José State,San Diego State,401022543,89,0,1.267470
9650,San Diego State,San José State,401022543,88,0,1.313373
9651,San José State,San Diego State,401022543,71,0,2.093732
9652,San Diego State,San José State,401022543,93,3,1.083856
9653,San José State,San Diego State,401022543,75,0,1.910118
9654,San Diego State,San José State,401022543,90,3,1.221567
9655,San José State,San Diego State,401022543,65,7,2.369152
9656,San Diego State,San José State,401022543,75,0,1.910118
9657,San José State,San Diego State,401022543,91,0,1.175663
9658,San Diego State,San José State,401022543,35,3,3.746255
9659,San José State,San Diego State,401022543,75,0,1.910118
9660,San Diego State,San José State,401022543,64,0,2.415055

In [5]:
df["PRE"] = df["points"] - df["expectedPoints"]
df

,offense,defense,game_id,start_distance,points,expectedPoints,PRE
0,Alabama,Louisville,401012246,65,7,2.369152,4.630848
1,Louisville,Alabama,401012246,75,0,1.910118,-1.910118
2,Alabama,Louisville,401012246,80,0,1.680601,-1.680601
3,Louisville,Alabama,401012246,83,0,1.542891,-1.542891
4,Alabama,Louisville,401012246,55,7,2.828186,4.171814
5,Louisville,Alabama,401012246,75,0,1.910118,-1.910118
6,Alabama,Louisville,401012246,75,7,1.910118,5.089882
7,Louisville,Alabama,401012246,86,0,1.405180,-1.405180
8,Alabama,Louisville,401012246,78,0,1.772408,-1.772408
9,Louisville,Alabama,401012246,80,0,1.680601,-1.680601
10,Alabama,Louisville,401012246,80,0,1.680601,-1.680601
11,Louisville,Alabama,401012246,85,0,1.451084,-1.451084
12,Alabama,Louisville,401012246,25,7,4.205289,2.794711
13,Louisville,Alabama,401012246,75,0,1.910118,-1.910118
14,Alabama,Louisville,401012246,63,7,2.460959,4.539041
15,Louisville,Alabama,401012246,96,7,0.946146,6.053854
16,Louisville,Alabama,401012246,76,0,1.864214,-1.864214
17,Alabama,Louisville,401012246,58,3,2.690476,0.309524
18,Louisville,Alabama,401012246,94,0,1.037953,-1.037953
19,Alabama,Louisville,401012246,79,0,1.726504,-1.726504
20,Louisville,Alabama,401012246,80,-7,1.680601,-8.680601
21,Louisville,Alabama,401012246,37,0,3.654448,-3.654448
22,Alabama,Louisville,401012246,95,0,0.992050,-0.992050
23,Louisville,Alabama,401012246,52,7,2.965896,4.034104
24,Washington,Auburn,401012248,75,0,1.910118,-1.910118
25,Auburn,Washington,401012248,36,7,3.700351,3.299649
26,Washington,Auburn,401012248,75,0,1.910118,-1.910118
27,Auburn,Washington,401012248,63,3,2.460959,0.539041
28,Washington,Auburn,401012248,75,3,1.910118,1.089882
29,Auburn,Washington,401012248,76,0,1.864214,-1.864214
...,...,...,...,...,...,...,...
9631,Hawai'i,Nevada,401022542,92,0,1.129760,-1.129760
9632,Nevada,Hawai'i,401022542,40,0,3.516737,-3.516737
9633,Hawai'i,Nevada,401022542,75,0,1.910118,-1.910118
9634,Nevada,Hawai'i,401022542,80,7,1.680601,5.319399
9635,Hawai'i,Nevada,401022542,75,0,1.910118,-1.910118
9636,Nevada,Hawai'i,401022542,97,0,0.900243,-0.900243
9637,Hawai'i,Nevada,401022542,61,0,2.552766,-2.552766
9638,Hawai'i,Nevada,401022542,18,0,4.526613,-4.526613
9639,Nevada,Hawai'i,401022542,81,7,1.634697,5.365303
9640,Hawai'i,Nevada,401022542,75,0,1.910118,-1.910118
9641,Nevada,Hawai'i,401022542,31,0,3.929868,-3.929868
9642,Hawai'i,Nevada,401022542,80,7,1.680601,5.319399
9643,Nevada,Hawai'i,401022542,24,7,4.251192,2.748808
9644,San Diego State,San José State,401022543,75,0,1.910118,-1.910118
9645,San José State,San Diego State,401022543,77,3,1.818311,1.181689
9646,San Diego State,San José State,401022543,65,0,2.369152,-2.369152
9647,San José State,San Diego State,401022543,35,3,3.746255,-0.746255
9648,San Diego State,San José State,401022543,75,7,1.910118,5.089882
9649,San José State,San Diego State,401022543,89,0,1.267470,-1.267470
9650,San Diego State,San José State,401022543,88,0,1.313373,-1.313373
9651,San José State,San Diego State,401022543,71,0,2.093732,-2.093732
9652,San Diego State,San José State,401022543,93,3,1.083856,1.916144
9653,San José State,San Diego State,401022543,75,0,1.910118,-1.910118
9654,San Diego State,San José State,401022543,90,3,1.221567,1.778433
9655,San José State,San Diego State,401022543,65,7,2.369152,4.630848
9656,San Diego State,San José State,401022543,75,0,1.910118,-1.910118
9657,San José State,San Diego State,401022543,91,0,1.175663,-1.175663
9658,San Diego State,San José State,401022543,35,3,3.746255,-0.746255
9659,San José State,San Diego State,401022543,75,0,1.910118,-1.910118
9660,San Diego State,San José State,401022543,64,0,2.415055,-2.415055

In [6]:
teams_df = df.groupby(by=["offense"]).agg(["mean"])["PRE"]
teams_df.columns = ["OPRE"]
teams_df.index.name = "team"
teams_df

                       OPRE
team
Air Force         -0.037386
Akron             -0.805996
Alabama            1.768521
Appalachian State  0.655309
Arizona           -0.242635
Arizona State      0.609223
Arkansas          -0.521397
Arkansas State    -0.360100
Army               1.101578
Auburn            -0.428165
BYU               -0.016709
Ball State        -0.227757
Baylor             0.327302
Boise State        0.582520
Boston College     0.334867
Bowling Green     -0.177589
Buffalo            0.193400
California        -0.812966
Central Michigan  -0.812766
Charlotte         -0.449563
Cincinnati         0.257574
Clemson            0.930941
Coastal Carolina   0.548946
Colorado           0.285594
Colorado State    -0.324367
Connecticut       -0.649280
Duke              -0.247408
East Carolina     -0.917846
Eastern Michigan  -0.162411
Florida            0.168022
...                     ...
Tennessee         -0.429794
Texas              0.295340
Texas A&M          0.150321
Texas State       -0.974591
Texas Tech         0.734727
Toledo             0.056577
Troy               0.216732
Tulane            -0.531131
Tulsa             -0.958167
UAB                0.191792
UCF                1.685718
UCLA              -0.126314
UMass             -0.071917
UNLV               0.016483
USC               -0.182755
UT San Antonio    -0.963399
UTEP              -0.455363
Utah               0.114067
Utah State         0.597380
Vanderbilt        -0.216833
Virginia           0.280157
Virginia Tech     -0.210842
Wake Forest       -0.475039
Washington         0.574931
Washington State   1.353030
West Virginia      0.588695
Western Kentucky  -0.485066
Western Michigan   0.636377
Wisconsin          0.705551
Wyoming           -0.988619

[129 rows x 1 columns]

In [7]:
defenses = df.groupby(by=["defense"]).agg(["mean"])["PRE"]
defenses.columns = ["DPRE"]
defenses.index.name = "team"
defenses

                       DPRE
team
Air Force         -0.034339
Akron             -0.377049
Alabama           -1.122933
Appalachian State -0.888214
Arizona            0.172190
Arizona State      0.046989
Arkansas           0.022634
Arkansas State     0.235630
Army              -0.097059
Auburn            -0.718319
BYU                0.437945
Ball State         0.326588
Baylor             0.435848
Boise State       -0.715729
Boston College    -0.555047
Bowling Green      1.726902
Buffalo           -0.292686
California        -0.682830
Central Michigan   0.028612
Charlotte          0.216071
Cincinnati        -0.773919
Clemson           -1.057624
Coastal Carolina   1.183481
Colorado          -0.135686
Colorado State     0.186675
Connecticut        2.344521
Duke              -0.527706
East Carolina      0.176281
Eastern Michigan  -0.127588
Florida           -0.831031
...                     ...
Tennessee          0.508817
Texas             -0.281775
Texas A&M         -0.191324
Texas State       -0.162402
Texas Tech         0.145530
Toledo             0.672375
Troy              -0.158914
Tulane            -0.142364
Tulsa             -0.007396
UAB               -0.789441
UCF               -0.506938
UCLA               0.473072
UMass              1.230663
UNLV               0.855038
USC               -0.143881
UT San Antonio     0.077341
UTEP               0.472209
Utah              -0.708229
Utah State        -0.523142
Vanderbilt         0.131252
Virginia          -0.173432
Virginia Tech     -0.159400
Wake Forest        0.414883
Washington        -0.461423
Washington State  -0.221503
West Virginia     -0.278661
Western Kentucky   0.125793
Western Michigan   0.303580
Wisconsin         -0.224517
Wyoming            0.152023

[129 rows x 1 columns]

In [8]:
teams_df = pd.merge(teams_df, defenses, how="inner", left_index=True, right_index=True)
for index, row in teams_df.iterrows():
    print(index)
    print(row)

Air Force
OPRE   -0.037386
DPRE   -0.034339
Name: Air Force, dtype: float64
Akron
OPRE   -0.805996
DPRE   -0.377049
Name: Akron, dtype: float64
Alabama
OPRE    1.768521
DPRE   -1.122933
Name: Alabama, dtype: float64
Appalachian State
OPRE    0.655309
DPRE   -0.888214
Name: Appalachian State, dtype: float64
Arizona
OPRE   -0.242635
DPRE    0.172190
Name: Arizona, dtype: float64
Arizona State
OPRE    0.609223
DPRE    0.046989
Name: Arizona State, dtype: float64
Arkansas
OPRE   -0.521397
DPRE    0.022634
Name: Arkansas, dtype: float64
Arkansas State
OPRE   -0.36010
DPRE    0.23563
Name: Arkansas State, dtype: float64
Army
OPRE    1.101578
DPRE   -0.097059
Name: Army, dtype: float64
Auburn
OPRE   -0.428165
DPRE   -0.718319
Name: Auburn, dtype: float64
BYU
OPRE   -0.016709
DPRE    0.437945
Name: BYU, dtype: float64
Ball State
OPRE   -0.227757
DPRE    0.326588
Name: Ball State, dtype: float64
Baylor
OPRE    0.327302
DPRE    0.435848
Name: Baylor, dtype: float64
Boise State
OPRE    0.582520
DPRE   -0.715729
Name: Boise State, dtype: float64
Boston College
OPRE    0.334867
DPRE   -0.555047
Name: Boston College, dtype: float64
Bowling Green
OPRE   -0.177589
DPRE    1.726902
Name: Bowling Green, dtype: float64
Buffalo
OPRE    0.193400
DPRE   -0.292686
Name: Buffalo, dtype: float64
California
OPRE   -0.812966
DPRE   -0.682830
Name: California, dtype: float64
Central Michigan
OPRE   -0.812766
DPRE    0.028612
Name: Central Michigan, dtype: float64
Charlotte
OPRE   -0.449563
DPRE    0.216071
Name: Charlotte, dtype: float64
Cincinnati
OPRE    0.257574
DPRE   -0.773919
Name: Cincinnati, dtype: float64
Clemson
OPRE    0.930941
DPRE   -1.057624
Name: Clemson, dtype: float64
Coastal Carolina
OPRE    0.548946
DPRE    1.183481
Name: Coastal Carolina, dtype: float64
Colorado
OPRE    0.285594
DPRE   -0.135686
Name: Colorado, dtype: float64
Colorado State
OPRE   -0.324367
DPRE    0.186675
Name: Colorado State, dtype: float64
Connecticut
OPRE   -0.649280
DPRE    2.344521
Name: Connecticut, dtype: float64
Duke
OPRE   -0.247408
DPRE   -0.527706
Name: Duke, dtype: float64
East Carolina
OPRE   -0.917846
DPRE    0.176281
Name: East Carolina, dtype: float64
Eastern Michigan
OPRE   -0.162411
DPRE   -0.127588
Name: Eastern Michigan, dtype: float64
Florida
OPRE    0.168022
DPRE   -0.831031
Name: Florida, dtype: float64
Florida Atlantic
OPRE   -0.153698
DPRE    0.602812
Name: Florida Atlantic, dtype: float64
Florida International
OPRE    0.763466
DPRE    0.074289
Name: Florida International, dtype: float64
Florida State
OPRE   -0.507277
DPRE   -0.837775
Name: Florida State, dtype: float64
Fresno State
OPRE    0.367543
DPRE   -0.849435
Name: Fresno State, dtype: float64
Georgia
OPRE    1.196647
DPRE   -0.795909
Name: Georgia, dtype: float64
Georgia Southern
OPRE   -0.198876
DPRE   -0.086939
Name: Georgia Southern, dtype: float64
Georgia State
OPRE   -0.022964
DPRE    1.141738
Name: Georgia State, dtype: float64
Georgia Tech
OPRE    0.980063
DPRE    0.319482
Name: Georgia Tech, dtype: float64
Hawai'i
OPRE    0.559252
DPRE    0.558394
Name: Hawai'i, dtype: float64
Houston
OPRE    0.911927
DPRE   -0.064632
Name: Houston, dtype: float64
Illinois
OPRE   -0.338543
DPRE    0.841427
Name: Illinois, dtype: float64
Indiana
OPRE    0.011040
DPRE    0.270164
Name: Indiana, dtype: float64
Iowa
OPRE    0.430235
DPRE   -1.012383
Name: Iowa, dtype: float64
Iowa State
OPRE   -0.055595
DPRE   -0.278728
Name: Iowa State, dtype: float64
Kansas
OPRE   -0.475594
DPRE   -0.047575
Name: Kansas, dtype: float64
Kansas State
OPRE   -0.056156
DPRE    0.025405
Name: Kansas State, dtype: float64
Kent State
OPRE   -0.471670
DPRE    0.974918
Name: Kent State, dtype: float64
Kentucky
OPRE   -0.323839
DPRE   -1.055850
Name: Kentucky, dtype: float64
LSU
OPRE    0.016889
DPRE   -0.640888
Name: LSU, dtype: float64
Liberty
OPRE    0.041851
DPRE    0.050910
Name: Liberty, dtype: float64
Louisiana
OPRE   -0.019895
DPRE    1.654067
Name: Louisiana, dtype: float64
Louisiana Monroe
OPRE   -0.344342
DPRE    0.810902
Name: Louisiana Monroe, dtype: float64
Louisiana Tech
OPRE   -0.261680
DPRE   -0.314701
Name: Louisiana Tech, dtype: float64
Louisville
OPRE   -0.885467
DPRE    0.950220
Name: Louisville, dtype: float64
Marshall
OPRE   -0.305236
DPRE   -0.318565
Name: Marshall, dtype: float64
Maryland
OPRE   -0.302264
DPRE   -0.607594
Name: Maryland, dtype: float64
Memphis
OPRE    0.834097
DPRE    0.436774
Name: Memphis, dtype: float64
Miami
OPRE    0.046865
DPRE   -1.044295
Name: Miami, dtype: float64
Miami (OH)
OPRE    0.336947
DPRE   -0.066996
Name: Miami (OH), dtype: float64
Michigan
OPRE    0.662725
DPRE   -1.201848
Name: Michigan, dtype: float64
Michigan State
OPRE   -0.449793
DPRE   -0.561643
Name: Michigan State, dtype: float64
Middle Tennessee
OPRE   -0.726723
DPRE    0.433538
Name: Middle Tennessee, dtype: float64
Minnesota
OPRE   -0.447325
DPRE    0.694413
Name: Minnesota, dtype: float64
Mississippi State
OPRE    0.063292
DPRE   -0.945777
Name: Mississippi State, dtype: float64
Missouri
OPRE    0.331942
DPRE    0.092682
Name: Missouri, dtype: float64
NC State
OPRE    0.450347
DPRE   -0.441028
Name: NC State, dtype: float64
Navy
OPRE   -0.007900
DPRE    0.812819
Name: Navy, dtype: float64
Nebraska
OPRE   -0.185455
DPRE    0.490172
Name: Nebraska, dtype: float64
Nevada
OPRE   -0.438667
DPRE   -0.029221
Name: Nevada, dtype: float64
New Mexico
OPRE    0.028900
DPRE    0.421286
Name: New Mexico, dtype: float64
North Carolina
OPRE   -0.807626
DPRE    0.165939
Name: North Carolina, dtype: float64
North Texas
OPRE    0.281139
DPRE   -0.711977
Name: North Texas, dtype: float64
Northern Illinois
OPRE   -0.907565
DPRE   -0.489838
Name: Northern Illinois, dtype: float64
Northwestern
OPRE   -0.575299
DPRE   -0.478634
Name: Northwestern, dtype: float64
Notre Dame
OPRE    0.521475
DPRE   -0.690215
Name: Notre Dame, dtype: float64
Ohio
OPRE    1.127608
DPRE    0.653165
Name: Ohio, dtype: float64
Ohio State
OPRE    1.065134
DPRE   -0.264397
Name: Ohio State, dtype: float64
Oklahoma
OPRE    1.979100
DPRE    0.279567
Name: Oklahoma, dtype: float64
Oklahoma State
OPRE    0.484508
DPRE    0.187158
Name: Oklahoma State, dtype: float64
Old Dominion
OPRE    0.124339
DPRE    0.972719
Name: Old Dominion, dtype: float64
Ole Miss
OPRE    0.613231
DPRE    0.572720
Name: Ole Miss, dtype: float64
Oregon
OPRE    0.445994
DPRE   -0.219041
Name: Oregon, dtype: float64
Oregon State
OPRE   -0.436826
DPRE    2.127956
Name: Oregon State, dtype: float64
Penn State
OPRE    0.707038
DPRE   -0.579623
Name: Penn State, dtype: float64
Pittsburgh
OPRE   -0.454526
DPRE    0.349341
Name: Pittsburgh, dtype: float64
Purdue
OPRE    0.671284
DPRE   -0.291592
Name: Purdue, dtype: float64
Rice
OPRE   -1.043483
DPRE    0.902903
Name: Rice, dtype: float64
Rutgers
OPRE   -1.112462
DPRE    0.201004
Name: Rutgers, dtype: float64
SMU
OPRE   -1.031794
DPRE    0.524530
Name: SMU, dtype: float64
San Diego State
OPRE   -0.426466
DPRE   -0.706090
Name: San Diego State, dtype: float64
San José State
OPRE   -1.165201
DPRE    0.386313
Name: San José State, dtype: float64
South Alabama
OPRE   -0.588981
DPRE    0.913415
Name: South Alabama, dtype: float64
South Carolina
OPRE    0.242769
DPRE   -0.008686
Name: South Carolina, dtype: float64
South Florida
OPRE    0.403199
DPRE    0.038524
Name: South Florida, dtype: float64
Southern Mississippi
OPRE   -0.455673
DPRE   -0.621500
Name: Southern Mississippi, dtype: float64
Stanford
OPRE   -0.162224
DPRE    0.001571
Name: Stanford, dtype: float64
Syracuse
OPRE   -0.008425
DPRE   -0.231654
Name: Syracuse, dtype: float64
TCU
OPRE   -0.747545
DPRE   -0.350221
Name: TCU, dtype: float64
Temple
OPRE   -0.245374
DPRE   -0.947183
Name: Temple, dtype: float64
Tennessee
OPRE   -0.429794
DPRE    0.508817
Name: Tennessee, dtype: float64
Texas
OPRE    0.295340
DPRE   -0.281775
Name: Texas, dtype: float64
Texas A&M
OPRE    0.150321
DPRE   -0.191324
Name: Texas A&M, dtype: float64
Texas State
OPRE   -0.974591
DPRE   -0.162402
Name: Texas State, dtype: float64
Texas Tech
OPRE    0.734727
DPRE    0.145530
Name: Texas Tech, dtype: float64
Toledo
OPRE    0.056577
DPRE    0.672375
Name: Toledo, dtype: float64
Troy
OPRE    0.216732
DPRE   -0.158914
Name: Troy, dtype: float64
Tulane
OPRE   -0.531131
DPRE   -0.142364
Name: Tulane, dtype: float64
Tulsa
OPRE   -0.958167
DPRE   -0.007396
Name: Tulsa, dtype: float64
UAB
OPRE    0.191792
DPRE   -0.789441
Name: UAB, dtype: float64
UCF
OPRE    1.685718
DPRE   -0.506938
Name: UCF, dtype: float64
UCLA
OPRE   -0.126314
DPRE    0.473072
Name: UCLA, dtype: float64
UMass
OPRE   -0.071917
DPRE    1.230663
Name: UMass, dtype: float64
UNLV
OPRE    0.016483
DPRE    0.855038
Name: UNLV, dtype: float64
USC
OPRE   -0.182755
DPRE   -0.143881
Name: USC, dtype: float64
UT San Antonio
OPRE   -0.963399
DPRE    0.077341
Name: UT San Antonio, dtype: float64
UTEP
OPRE   -0.455363
DPRE    0.472209
Name: UTEP, dtype: float64
Utah
OPRE    0.114067
DPRE   -0.708229
Name: Utah, dtype: float64
Utah State
OPRE    0.597380
DPRE   -0.523142
Name: Utah State, dtype: float64
Vanderbilt
OPRE   -0.216833
DPRE    0.131252
Name: Vanderbilt, dtype: float64
Virginia
OPRE    0.280157
DPRE   -0.173432
Name: Virginia, dtype: float64
Virginia Tech
OPRE   -0.210842
DPRE   -0.159400
Name: Virginia Tech, dtype: float64
Wake Forest
OPRE   -0.475039
DPRE    0.414883
Name: Wake Forest, dtype: float64
Washington
OPRE    0.574931
DPRE   -0.461423
Name: Washington, dtype: float64
Washington State
OPRE    1.353030
DPRE   -0.221503
Name: Washington State, dtype: float64
West Virginia
OPRE    0.588695
DPRE   -0.278661
Name: West Virginia, dtype: float64
Western Kentucky
OPRE   -0.485066
DPRE    0.125793
Name: Western Kentucky, dtype: float64
Western Michigan
OPRE    0.636377
DPRE    0.303580
Name: Western Michigan, dtype: float64
Wisconsin
OPRE    0.705551
DPRE   -0.224517
Name: Wisconsin, dtype: float64
Wyoming
OPRE   -0.988619
DPRE    0.152023
Name: Wyoming, dtype: float64

In [9]:
teams_df.sort_values(by="OPRE", ascending=False).head(10)

                      OPRE      DPRE
team
Oklahoma          1.979100  0.279567
Alabama           1.768521 -1.122933
UCF               1.685718 -0.506938
Washington State  1.353030 -0.221503
Georgia           1.196647 -0.795909
Ohio              1.127608  0.653165
Army              1.101578 -0.097059
Ohio State        1.065134 -0.264397
Georgia Tech      0.980063  0.319482
Clemson           0.930941 -1.057624

In [10]:
teams_df.sort_values(by="DPRE").head(10)

                       OPRE      DPRE
team
Michigan           0.662725 -1.201848
Alabama            1.768521 -1.122933
Clemson            0.930941 -1.057624
Kentucky          -0.323839 -1.055850
Miami              0.046865 -1.044295
Iowa               0.430235 -1.012383
Temple            -0.245374 -0.947183
Mississippi State  0.063292 -0.945777
Appalachian State  0.655309 -0.888214
Fresno State       0.367543 -0.849435

In [11]:
df

,offense,defense,game_id,start_distance,points,expectedPoints,PRE
0,Alabama,Louisville,401012246,65,7,2.369152,4.630848
1,Louisville,Alabama,401012246,75,0,1.910118,-1.910118
2,Alabama,Louisville,401012246,80,0,1.680601,-1.680601
3,Louisville,Alabama,401012246,83,0,1.542891,-1.542891
4,Alabama,Louisville,401012246,55,7,2.828186,4.171814
5,Louisville,Alabama,401012246,75,0,1.910118,-1.910118
6,Alabama,Louisville,401012246,75,7,1.910118,5.089882
7,Louisville,Alabama,401012246,86,0,1.405180,-1.405180
8,Alabama,Louisville,401012246,78,0,1.772408,-1.772408
9,Louisville,Alabama,401012246,80,0,1.680601,-1.680601
10,Alabama,Louisville,401012246,80,0,1.680601,-1.680601
11,Louisville,Alabama,401012246,85,0,1.451084,-1.451084
12,Alabama,Louisville,401012246,25,7,4.205289,2.794711
13,Louisville,Alabama,401012246,75,0,1.910118,-1.910118
14,Alabama,Louisville,401012246,63,7,2.460959,4.539041
15,Louisville,Alabama,401012246,96,7,0.946146,6.053854
16,Louisville,Alabama,401012246,76,0,1.864214,-1.864214
17,Alabama,Louisville,401012246,58,3,2.690476,0.309524
18,Louisville,Alabama,401012246,94,0,1.037953,-1.037953
19,Alabama,Louisville,401012246,79,0,1.726504,-1.726504
20,Louisville,Alabama,401012246,80,-7,1.680601,-8.680601
21,Louisville,Alabama,401012246,37,0,3.654448,-3.654448
22,Alabama,Louisville,401012246,95,0,0.992050,-0.992050
23,Louisville,Alabama,401012246,52,7,2.965896,4.034104
24,Washington,Auburn,401012248,75,0,1.910118,-1.910118
25,Auburn,Washington,401012248,36,7,3.700351,3.299649
26,Washington,Auburn,401012248,75,0,1.910118,-1.910118
27,Auburn,Washington,401012248,63,3,2.460959,0.539041
28,Washington,Auburn,401012248,75,3,1.910118,1.089882
29,Auburn,Washington,401012248,76,0,1.864214,-1.864214
...,...,...,...,...,...,...,...
9631,Hawai'i,Nevada,401022542,92,0,1.129760,-1.129760
9632,Nevada,Hawai'i,401022542,40,0,3.516737,-3.516737
9633,Hawai'i,Nevada,401022542,75,0,1.910118,-1.910118
9634,Nevada,Hawai'i,401022542,80,7,1.680601,5.319399
9635,Hawai'i,Nevada,401022542,75,0,1.910118,-1.910118
9636,Nevada,Hawai'i,401022542,97,0,0.900243,-0.900243
9637,Hawai'i,Nevada,401022542,61,0,2.552766,-2.552766
9638,Hawai'i,Nevada,401022542,18,0,4.526613,-4.526613
9639,Nevada,Hawai'i,401022542,81,7,1.634697,5.365303
9640,Hawai'i,Nevada,401022542,75,0,1.910118,-1.910118
9641,Nevada,Hawai'i,401022542,31,0,3.929868,-3.929868
9642,Hawai'i,Nevada,401022542,80,7,1.680601,5.319399
9643,Nevada,Hawai'i,401022542,24,7,4.251192,2.748808
9644,San Diego State,San José State,401022543,75,0,1.910118,-1.910118
9645,San José State,San Diego State,401022543,77,3,1.818311,1.181689
9646,San Diego State,San José State,401022543,65,0,2.369152,-2.369152
9647,San José State,San Diego State,401022543,35,3,3.746255,-0.746255
9648,San Diego State,San José State,401022543,75,7,1.910118,5.089882
9649,San José State,San Diego State,401022543,89,0,1.267470,-1.267470
9650,San Diego State,San José State,401022543,88,0,1.313373,-1.313373
9651,San José State,San Diego State,401022543,71,0,2.093732,-2.093732
9652,San Diego State,San José State,401022543,93,3,1.083856,1.916144
9653,San José State,San Diego State,401022543,75,0,1.910118,-1.910118
9654,San Diego State,San José State,401022543,90,3,1.221567,1.778433
9655,San José State,San Diego State,401022543,65,7,2.369152,4.630848
9656,San Diego State,San José State,401022543,75,0,1.910118,-1.910118
9657,San José State,San Diego State,401022543,91,0,1.175663,-1.175663
9658,San Diego State,San José State,401022543,35,3,3.746255,-0.746255
9659,San José State,San Diego State,401022543,75,0,1.910118,-1.910118
9660,San Diego State,San José State,401022543,64,0,2.415055,-2.415055

In [12]:
df["off_oppAdj"] = 0.0
df["def_oppAdj"] = 0.0
for index, row in df.iterrows():
    df.at[index, "off_oppAdj"] = df.at[index, "PRE"] - teams_df.at[row["defense"], "DPRE"]
    df.at[index, "def_oppAdj"] = df.at[index, "PRE"] - teams_df.at[row["offense"], "OPRE"]
df

,offense,defense,game_id,start_distance,points,expectedPoints,PRE,off_oppAdj,def_oppAdj
0,Alabama,Louisville,401012246,65,7,2.369152,4.630848,3.680628,2.862327
1,Louisville,Alabama,401012246,75,0,1.910118,-1.910118,-0.787185,-1.024651
2,Alabama,Louisville,401012246,80,0,1.680601,-1.680601,-2.630821,-3.449122
3,Louisville,Alabama,401012246,83,0,1.542891,-1.542891,-0.419958,-0.657423
4,Alabama,Louisville,401012246,55,7,2.828186,4.171814,3.221594,2.403293
5,Louisville,Alabama,401012246,75,0,1.910118,-1.910118,-0.787185,-1.024651
6,Alabama,Louisville,401012246,75,7,1.910118,5.089882,4.139662,3.321361
7,Louisville,Alabama,401012246,86,0,1.405180,-1.405180,-0.282247,-0.519713
8,Alabama,Louisville,401012246,78,0,1.772408,-1.772408,-2.722628,-3.540929
9,Louisville,Alabama,401012246,80,0,1.680601,-1.680601,-0.557668,-0.795133
10,Alabama,Louisville,401012246,80,0,1.680601,-1.680601,-2.630821,-3.449122
11,Louisville,Alabama,401012246,85,0,1.451084,-1.451084,-0.328151,-0.565616
12,Alabama,Louisville,401012246,25,7,4.205289,2.794711,1.844491,1.026190
13,Louisville,Alabama,401012246,75,0,1.910118,-1.910118,-0.787185,-1.024651
14,Alabama,Louisville,401012246,63,7,2.460959,4.539041,3.588821,2.770520
15,Louisville,Alabama,401012246,96,7,0.946146,6.053854,7.176787,6.939321
16,Louisville,Alabama,401012246,76,0,1.864214,-1.864214,-0.741281,-0.978747
17,Alabama,Louisville,401012246,58,3,2.690476,0.309524,-0.640696,-1.458997
18,Louisville,Alabama,401012246,94,0,1.037953,-1.037953,0.084980,-0.152486
19,Alabama,Louisville,401012246,79,0,1.726504,-1.726504,-2.676724,-3.495025
20,Louisville,Alabama,401012246,80,-7,1.680601,-8.680601,-7.557668,-7.795133
21,Louisville,Alabama,401012246,37,0,3.654448,-3.654448,-2.531515,-2.768980
22,Alabama,Louisville,401012246,95,0,0.992050,-0.992050,-1.942270,-2.760571
23,Louisville,Alabama,401012246,52,7,2.965896,4.034104,5.157037,4.919571
24,Washington,Auburn,401012248,75,0,1.910118,-1.910118,-1.191799,-2.485049
25,Auburn,Washington,401012248,36,7,3.700351,3.299649,3.761072,3.727814
26,Washington,Auburn,401012248,75,0,1.910118,-1.910118,-1.191799,-2.485049
27,Auburn,Washington,401012248,63,3,2.460959,0.539041,1.000464,0.967206
28,Washington,Auburn,401012248,75,3,1.910118,1.089882,1.808201,0.514951
29,Auburn,Washington,401012248,76,0,1.864214,-1.864214,-1.402792,-1.436049
...,...,...,...,...,...,...,...,...,...
9631,Hawai'i,Nevada,401022542,92,0,1.129760,-1.129760,-1.100539,-1.689012
9632,Nevada,Hawai'i,401022542,40,0,3.516737,-3.516737,-4.075132,-3.078070
9633,Hawai'i,Nevada,401022542,75,0,1.910118,-1.910118,-1.880897,-2.469370
9634,Nevada,Hawai'i,401022542,80,7,1.680601,5.319399,4.761005,5.758066
9635,Hawai'i,Nevada,401022542,75,0,1.910118,-1.910118,-1.880897,-2.469370
9636,Nevada,Hawai'i,401022542,97,0,0.900243,-0.900243,-1.458637,-0.461576
9637,Hawai'i,Nevada,401022542,61,0,2.552766,-2.552766,-2.523545,-3.112018
9638,Hawai'i,Nevada,401022542,18,0,4.526613,-4.526613,-4.497392,-5.085865
9639,Nevada,Hawai'i,401022542,81,7,1.634697,5.365303,4.806908,5.803970
9640,Hawai'i,Nevada,401022542,75,0,1.910118,-1.910118,-1.880897,-2.469370
9641,Nevada,Hawai'i,401022542,31,0,3.929868,-3.929868,-4.488263,-3.491201
9642,Hawai'i,Nevada,401022542,80,7,1.680601,5.319399,5.348620,4.760147
9643,Nevada,Hawai'i,401022542,24,7,4.251192,2.748808,2.190413,3.187475
9644,San Diego State,San José State,401022543,75,0,1.910118,-1.910118,-2.296431,-1.483651
9645,San José State,San Diego State,401022543,77,3,1.818311,1.181689,1.887779,2.346890
9646,San Diego State,San José State,401022543,65,0,2.369152,-2.369152,-2.755465,-1.942686
9647,San José State,San Diego State,401022543,35,3,3.746255,-0.746255,-0.040164,0.418946
9648,San Diego State,San José State,401022543,75,7,1.910118,5.089882,4.703569,5.516349
9649,San José State,San Diego State,401022543,89,0,1.267470,-1.267470,-0.561380,-0.102269
9650,San Diego State,San José State,401022543,88,0,1.313373,-1.313373,-1.699686,-0.886907
9651,San José State,San Diego State,401022543,71,0,2.093732,-2.093732,-1.387641,-0.928531
9652,San Diego State,San José State,401022543,93,3,1.083856,1.916144,1.529831,2.342610
9653,San José State,San Diego State,401022543,75,0,1.910118,-1.910118,-1.204028,-0.744917
9654,San Diego State,San José State,401022543,90,3,1.221567,1.778433,1.392120,2.204900
9655,San José State,San Diego State,401022543,65,7,2.369152,4.630848,5.336938,5.796049
9656,San Diego State,San José State,401022543,75,0,1.910118,-1.910118,-2.296431,-1.483651
9657,San José State,San Diego State,401022543,91,0,1.175663,-1.175663,-0.469573,-0.010462
9658,San Diego State,San José State,401022543,35,3,3.746255,-0.746255,-1.132568,-0.319788
9659,San José State,San Diego State,401022543,75,0,1.910118,-1.910118,-1.204028,-0.744917
9660,San Diego State,San José State,401022543,64,0,2.415055,-2.415055,-2.801368,-1.988589

In [13]:
teams_df[["off_aPPD"]] = df.groupby(by="offense").agg(["mean"])["off_oppAdj"]
teams_df[["def_aPPD"]] = df.groupby(by="defense").agg(["mean"])["def_oppAdj"]
teams_df

                       OPRE      DPRE  off_aPPD  def_aPPD
team
Air Force         -0.037386 -0.034339 -0.157724  0.032333
Akron             -0.805996 -0.377049 -0.789907 -0.226025
Alabama            1.768521 -1.122933  1.320888 -0.990042
Appalachian State  0.655309 -0.888214  0.183936 -0.743969
Arizona           -0.242635  0.172190 -0.382682  0.224289
Arizona State      0.609223  0.046989  0.550705  0.313070
Arkansas          -0.521397  0.022634 -0.177633 -0.076735
Arkansas State    -0.360100  0.235630 -0.301418 -0.014576
Army               1.101578 -0.097059  1.049902 -0.291712
Auburn            -0.428165 -0.718319 -0.211535 -0.668981
BYU               -0.016709  0.437945  0.197199  0.241236
Ball State        -0.227757  0.326588 -0.239403  0.610000
Baylor             0.327302  0.435848  0.411583  0.293968
Boise State        0.582520 -0.715729  0.354425 -0.427997
Boston College     0.334867 -0.555047  0.169025 -0.420872
Bowling Green     -0.177589  1.726902 -0.293255  1.309737
Buffalo            0.193400 -0.292686  0.238992  0.089029
California        -0.812966 -0.682830 -1.308188 -0.447849
Central Michigan  -0.812766  0.028612 -0.544872  0.233324
Charlotte         -0.449563  0.216071 -0.679663  0.331541
Cincinnati         0.257574 -0.773919 -0.099254 -0.661023
Clemson            0.930941 -1.057624  0.949869 -1.177773
Coastal Carolina   0.548946  1.183481  0.105974  1.153466
Colorado           0.285594 -0.135686  0.185470 -0.147851
Colorado State    -0.324367  0.186675 -0.386472  0.373053
Connecticut       -0.649280  2.344521 -0.373493  1.783488
Duke              -0.247408 -0.527706 -0.228285 -0.801300
East Carolina     -0.917846  0.176281 -0.648400 -0.198128
Eastern Michigan  -0.162411 -0.127588 -0.083988 -0.078606
Florida            0.168022 -0.831031  0.397924 -0.624356
...                     ...       ...       ...       ...
Tennessee         -0.429794  0.508817  0.152996  0.053787
Texas              0.295340 -0.281775  0.391856 -0.260051
Texas A&M          0.150321 -0.191324  0.635836 -0.512570
Texas State       -0.974591 -0.162402 -1.558241  0.376911
Texas Tech         0.734727  0.145530  0.736120 -0.084818
Toledo             0.056577  0.672375  0.186045  0.721608
Troy               0.216732 -0.158914 -0.246405 -0.159651
Tulane            -0.531131 -0.142364 -0.470940 -0.036621
Tulsa             -0.958167 -0.007396 -0.809236 -0.152149
UAB                0.191792 -0.789441 -0.001343 -0.482206
UCF                1.685718 -0.506938  1.004209 -0.109741
UCLA              -0.126314  0.473072  0.212854  0.104170
UMass             -0.071917  1.230663 -0.251439  0.874365
UNLV               0.016483  0.855038 -0.045738  0.919606
USC               -0.182755 -0.143881 -0.147594 -0.352901
UT San Antonio    -0.963399  0.077341 -1.063081  0.396924
UTEP              -0.455363  0.472209 -0.557849  0.752441
Utah               0.114067 -0.708229  0.315970 -0.730651
Utah State         0.597380 -0.523142  0.390067 -0.221157
Vanderbilt        -0.216833  0.131252  0.235310  0.030409
Virginia           0.280157 -0.173432  0.124798 -0.362486
Virginia Tech     -0.210842 -0.159400 -0.045420  0.019669
Wake Forest       -0.475039  0.414883 -0.021322  0.426084
Washington         0.574931 -0.461423  0.738325 -0.583719
Washington State   1.353030 -0.221503  1.131198  0.192712
West Virginia      0.588695 -0.278661  0.527248 -0.276925
Western Kentucky  -0.485066  0.125793 -0.786089  0.297417
Western Michigan   0.636377  0.303580  0.469756  0.364216
Wisconsin          0.705551 -0.224517  0.669764 -0.200393
Wyoming           -0.988619  0.152023 -0.676812 -0.499573

[129 rows x 4 columns]

In [14]:
def printLeaders():
    print(teams_df.sort_values(by="off_aPPD", ascending=False).head(10))
    print(teams_df.sort_values(by="def_aPPD").head(10))

printLeaders()

                      OPRE      DPRE  off_aPPD  def_aPPD
team
Oklahoma          1.979100  0.279567  1.886705  0.263849
Alabama           1.768521 -1.122933  1.320888 -0.990042
Georgia           1.196647 -0.795909  1.137842 -0.703175
Washington State  1.353030 -0.221503  1.131198  0.192712
Army              1.101578 -0.097059  1.049902 -0.291712
UCF               1.685718 -0.506938  1.004209 -0.109741
Clemson           0.930941 -1.057624  0.949869 -1.177773
Ohio              1.127608  0.653165  0.827896  0.821471
Ohio State        1.065134 -0.264397  0.824045 -0.113429
Michigan          0.662725 -1.201848  0.823207 -1.127393
                       OPRE      DPRE  off_aPPD  def_aPPD
team
Clemson            0.930941 -1.057624  0.949869 -1.177773
Michigan           0.662725 -1.201848  0.823207 -1.127393
Alabama            1.768521 -1.122933  1.320888 -0.990042
Kentucky          -0.323839 -1.055850 -0.042741 -0.962292
Miami              0.046865 -1.044295  0.223710 -0.949898
Mississippi State  0.063292 -0.945777  0.359642 -0.834655
LSU                0.016889 -0.640888  0.616292 -0.826886
TCU               -0.747545 -0.350221 -0.773020 -0.816184
Iowa               0.430235 -1.012383  0.493105 -0.814479
Duke              -0.247408 -0.527706 -0.228285 -0.801300

In [15]:
def adjust():
    for index, row in df.iterrows():
        df.at[index, "off_oppAdj"] = df.at[index, "PRE"] - teams_df.at[row["defense"], "def_aPPD"]
        df.at[index, "def_oppAdj"] = df.at[index, "PRE"] - teams_df.at[row["offense"], "off_aPPD"]

    teams_df[["off_aPPD"]] = df.groupby(by="offense").agg(["mean"])["off_oppAdj"]
    teams_df[["def_aPPD"]] = df.groupby(by="defense").agg(["mean"])["def_oppAdj"]

In [16]:
for i in range(40):
    adjust()
    print(teams_df.at["Oklahoma", "off_aPPD"])
printLeaders()

2.1487901896891577
2.081819039144995
2.1530775298698357
2.1261442187582764
2.149571513353421
2.138755138774137
2.1471215739592386
2.1426734788428603
2.145866839508306
2.1439964288225815
2.145299801765836
2.1444952028929274
2.145065030777531
2.144708603984638
2.144974868295111
2.1448099781359296
2.14494196368319
2.1448607005473446
2.1449293297541696
2.1448858523146432
2.1449228329756695
2.144897400448686
2.1449178274966174
2.1449017282002916
2.144913196223405
2.1449024075451986
2.1449089107131565
2.144901432051308
2.144905140929348
2.1448998728568074
2.144901993988009
2.144898265530176
2.144899479556138
2.1448968450693893
2.144897539461651
2.14489568687931
2.1448960833630393
2.1448947885596237
2.1448950143401717
2.144894115167353
                      OPRE      DPRE  off_aPPD  def_aPPD
team
Oklahoma          1.979100  0.279567  2.144894  0.118958
Alabama           1.768521 -1.122933  1.703191 -1.504534
Georgia           1.196647 -0.795909  1.654651 -1.358859
Washington State  1.353030 -0.221503  1.352179  0.169616
UCF               1.685718 -0.506938  1.112321  0.101287
Missouri          0.331942  0.092682  1.058430 -0.598473
Army              1.101578 -0.097059  1.024943 -0.104538
Texas A&M         0.150321 -0.191324  1.023990 -0.725486
Georgia Tech      0.980063  0.319482  0.994831  0.496192
Ole Miss          0.613231  0.572720  0.971852  0.226180
                       OPRE      DPRE  off_aPPD  def_aPPD
team
Kentucky          -0.323839 -1.055850  0.359310 -1.626834
Alabama            1.768521 -1.122933  1.703191 -1.504534
Mississippi State  0.063292 -0.945777  0.780289 -1.416435
Clemson            0.930941 -1.057624  0.905015 -1.396383
Georgia            1.196647 -0.795909  1.654651 -1.358859
Florida            0.168022 -0.831031  0.852683 -1.324941
Michigan           0.662725 -1.201848  0.921399 -1.292969
LSU                0.016889 -0.640888  0.923786 -1.196815
Auburn            -0.428165 -0.718319  0.066904 -1.140377
Miami              0.046865 -1.044295  0.041084 -1.103630

In [17]:
teams_df["net_aPPD"] = teams_df["off_aPPD"] - teams_df["def_aPPD"]

In [18]:
teams_df.sort_values(by="net_aPPD", ascending=False).head(25).reset_index()

                 team      OPRE      DPRE  off_aPPD  def_aPPD  net_aPPD
0             Alabama  1.768521 -1.122933  1.703191 -1.504534  3.207725
1             Georgia  1.196647 -0.795909  1.654651 -1.358859  3.013510
2             Clemson  0.930941 -1.057624  0.905015 -1.396383  2.301398
3            Michigan  0.662725 -1.201848  0.921399 -1.292969  2.214368
4   Mississippi State  0.063292 -0.945777  0.780289 -1.416435  2.196724
5             Florida  0.168022 -0.831031  0.852683 -1.324941  2.177624
6                 LSU  0.016889 -0.640888  0.923786 -1.196815  2.120602
7            Oklahoma  1.979100  0.279567  2.144894  0.118958  2.025937
8            Kentucky -0.323839 -1.055850  0.359310 -1.626834  1.986144
9           Texas A&M  0.150321 -0.191324  1.023990 -0.725486  1.749476
10               Iowa  0.430235 -1.012383  0.684351 -1.047167  1.731519
11           Missouri  0.331942  0.092682  1.058430 -0.598473  1.656904
12     South Carolina  0.242769 -0.008686  0.819328 -0.821353  1.640681
13         Washington  0.574931 -0.461423  0.807534 -0.749501  1.557035
14      West Virginia  0.588695 -0.278661  0.921056 -0.572362  1.493418
15         Notre Dame  0.521475 -0.690215  0.576455 -0.799832  1.376287
16         Penn State  0.707038 -0.579623  0.766268 -0.554512  1.320780
17             Purdue  0.671284 -0.291592  0.814766 -0.502979  1.317745
18               Utah  0.114067 -0.708229  0.388210 -0.840127  1.228337
19         Ohio State  1.065134 -0.264397  0.960690 -0.267088  1.227778
20             Auburn -0.428165 -0.718319  0.066904 -1.140377  1.207282
21           NC State  0.450347 -0.441028  0.694218 -0.501150  1.195368
22   Washington State  1.353030 -0.221503  1.352179  0.169616  1.182564
23              Miami  0.046865 -1.044295  0.041084 -1.103630  1.144715
24               Army  1.101578 -0.097059  1.024943 -0.104538  1.129481

In [21]:
teams_df["AP"] = "NR"
teams_df

                       OPRE      DPRE  off_aPPD  def_aPPD  net_aPPD  AP
team
Air Force         -0.037386 -0.034339 -0.182085  0.313110 -0.495196  NR
Akron             -0.805996 -0.377049 -0.790290 -0.238068 -0.552222  NR
Alabama            1.768521 -1.122933  1.703191 -1.504534  3.207725  NR
Appalachian State  0.655309 -0.888214  0.057539 -0.746065  0.803604  NR
Arizona           -0.242635  0.172190 -0.401344  0.255255 -0.656598  NR
Arizona State      0.609223  0.046989  0.614312  0.195918  0.418394  NR
Arkansas          -0.521397  0.022634 -0.043401 -0.294367  0.250966  NR
Arkansas State    -0.360100  0.235630 -0.348716  0.211131 -0.559847  NR
Army               1.101578 -0.097059  1.024943 -0.104538  1.129481  NR
Auburn            -0.428165 -0.718319  0.066904 -1.140377  1.207282  NR
BYU               -0.016709  0.437945  0.029888  0.423922 -0.394033  NR
Ball State        -0.227757  0.326588 -0.200947  0.614164 -0.815111  NR
Baylor             0.327302  0.435848  0.523684  0.212208  0.311476  NR
Boise State        0.582520 -0.715729  0.478493 -0.235020  0.713513  NR
Boston College     0.334867 -0.555047  0.139695 -0.577906  0.717600  NR
Bowling Green     -0.177589  1.726902 -0.520945  1.417773 -1.938718  NR
Buffalo            0.193400 -0.292686  0.050448 -0.018552  0.068999  NR
California        -0.812966 -0.682830 -1.476257 -0.541033 -0.935224  NR
Central Michigan  -0.812766  0.028612 -0.471230  0.111424 -0.582654  NR
Charlotte         -0.449563  0.216071 -0.935607  0.740961 -1.676568  NR
Cincinnati         0.257574 -0.773919 -0.284858 -0.735867  0.451009  NR
Clemson            0.930941 -1.057624  0.905015 -1.396383  2.301398  NR
Coastal Carolina   0.548946  1.183481  0.062920  1.351137 -1.288217  NR
Colorado           0.285594 -0.135686  0.343456 -0.325400  0.668856  NR
Colorado State    -0.324367  0.186675 -0.239414  0.303264 -0.542678  NR
Connecticut       -0.649280  2.344521 -0.673404  2.286339 -2.959743  NR
Duke              -0.247408 -0.527706 -0.202872 -0.884197  0.681326  NR
East Carolina     -0.917846  0.176281 -1.206799  0.012258 -1.219058  NR
Eastern Michigan  -0.162411 -0.127588 -0.180905 -0.105298 -0.075607  NR
Florida            0.168022 -0.831031  0.852683 -1.324941  2.177624  NR
...                     ...       ...       ...       ...       ...  ..
Tennessee         -0.429794  0.508817  0.488257 -0.234095  0.722353  NR
Texas              0.295340 -0.281775  0.653679 -0.361159  1.014838  NR
Texas A&M          0.150321 -0.191324  1.023990 -0.725486  1.749476  NR
Texas State       -0.974591 -0.162402 -1.849673  0.430299 -2.279972  NR
Texas Tech         0.734727  0.145530  0.859694 -0.161083  1.020777  NR
Toledo             0.056577  0.672375  0.171387  0.966765 -0.795378  NR
Troy               0.216732 -0.158914 -0.383447  0.021054 -0.404501  NR
Tulane            -0.531131 -0.142364 -0.593904  0.132215 -0.726118  NR
Tulsa             -0.958167 -0.007396 -1.016797 -0.107097 -0.909700  NR
UAB                0.191792 -0.789441 -0.281509 -0.224031 -0.057478  NR
UCF                1.685718 -0.506938  1.112321  0.101287  1.011034  NR
UCLA              -0.126314  0.473072  0.214631  0.280769 -0.066138  NR
UMass             -0.071917  1.230663 -0.607769  1.290808 -1.898576  NR
UNLV               0.016483  0.855038 -0.128620  1.001499 -1.130119  NR
USC               -0.182755 -0.143881 -0.139225 -0.449348  0.310124  NR
UT San Antonio    -0.963399  0.077341 -1.248113  0.586517 -1.834631  NR
UTEP              -0.455363  0.472209 -0.666783  0.711652 -1.378435  NR
Utah               0.114067 -0.708229  0.388210 -0.840127  1.228337  NR
Utah State         0.597380 -0.523142  0.498573 -0.251384  0.749957  NR
Vanderbilt        -0.216833  0.131252  0.620406 -0.222321  0.842726  NR
Virginia           0.280157 -0.173432  0.197157 -0.490418  0.687575  NR
Virginia Tech     -0.210842 -0.159400 -0.242307 -0.005994 -0.236313  NR
Wake Forest       -0.475039  0.414883 -0.052945  0.516147 -0.569092  NR
Washington         0.574931 -0.461423  0.807534 -0.749501  1.557035  NR
Washington State   1.353030 -0.221503  1.352179  0.169616  1.182564  NR
West Virginia      0.588695 -0.278661  0.921056 -0.572362  1.493418  NR
Western Kentucky  -0.485066  0.125793 -1.053421  0.468971 -1.522392  NR
Western Michigan   0.636377  0.303580  0.446316  0.474152 -0.027836  NR
Wisconsin          0.705551 -0.224517  0.691412 -0.210240  0.901653  NR
Wyoming           -0.988619  0.152023 -0.877778 -0.521668 -0.356110  NR

[129 rows x 6 columns]

In [22]:
teams_df.to_csv("Data/teams_aPPD.tsv", sep="\t")