In [1]:
SEASON = 2018

START_BETTING = 5
END_BETTING = 11

BET_THRESHOLD = 0.5
HFA = 2.5

In [2]:
import pandas as pd

pd.set_option('display.max_columns', 500)  # prints the df properly in console instead of splitting up columns
pd.set_option('display.width', 1000)

df = pd.read_json("https://api.collegefootballdata.com/games?year=" + str(SEASON))
df = df[(df.away_conference.notnull()) & (df.home_conference.notnull())]
df = df[["id", "start_date", "week", "away_team", "away_points", "home_team", "home_points"]]
df = df.set_index("id")
df.index = df.index.rename("game_id")
df

                         start_date  week              away_team  away_points         home_team  home_points
game_id
401022510  2018-08-25T23:30:00.000Z     1                Hawai'i           43    Colorado State           34
401013437  2018-08-26T02:00:00.000Z     1                Wyoming           29  New Mexico State            7
401013328  2018-08-30T23:00:00.000Z     1       New Mexico State           10         Minnesota           48
401019470  2018-08-30T23:00:00.000Z     1                    UCF           56       Connecticut           17
401013086  2018-08-31T00:00:00.000Z     1            Wake Forest           23            Tulane           17
401013342  2018-08-31T00:00:00.000Z     1           Northwestern           31            Purdue           27
401020673  2018-08-31T22:00:00.000Z     1               Syracuse           55  Western Michigan           42
401012880  2018-08-31T23:00:00.000Z     1             Utah State           31    Michigan State           38
401013089  2018-08-31T23:00:00.000Z     1                   Army           14              Duke           34
401022512  2018-09-01T01:00:00.000Z     1        San Diego State           10          Stanford           31
401013354  2018-09-01T01:00:00.000Z     1       Western Kentucky            3         Wisconsin           34
401012680  2018-09-01T01:30:00.000Z     1               Colorado           45    Colorado State           13
401012820  2018-09-01T16:00:00.000Z     1            Texas State            7           Rutgers           35
401013065  2018-09-01T16:00:00.000Z     1       Florida Atlantic           14          Oklahoma           63
401012804  2018-09-01T16:00:00.000Z     1             Kent State           24          Illinois           31
401012872  2018-09-01T16:00:00.000Z     1                  Texas           29          Maryland           34
401012256  2018-09-01T16:00:00.000Z     1       Coastal Carolina           15    South Carolina           49
401014977  2018-09-01T16:00:00.000Z     1                Houston           45              Rice           27
401012253  2018-09-01T16:00:00.000Z     1               Ole Miss           47        Texas Tech           27
401012682  2018-09-01T16:00:00.000Z     1           Oregon State           31        Ohio State           77
401013087  2018-09-01T17:00:00.000Z     1                  UMass           21    Boston College           55
401013349  2018-09-01T19:30:00.000Z     1      Appalachian State           38        Penn State           45
401012683  2018-09-01T19:30:00.000Z     1       Washington State           41           Wyoming           19
401012257  2018-09-01T19:30:00.000Z     1          West Virginia           40         Tennessee           14
401012248  2018-09-01T19:30:00.000Z     1             Washington           16            Auburn           21
401012251  2018-09-01T19:30:00.000Z     1       Central Michigan           20          Kentucky           35
401012862  2018-09-01T19:40:00.000Z     1      Northern Illinois            7              Iowa           33
401012684  2018-09-01T20:00:00.000Z     1         North Carolina           17        California           24
401012678  2018-09-01T20:00:00.000Z     1                   UNLV           21               USC           43
401013448  2018-09-01T22:00:00.000Z     1           Old Dominion           10           Liberty           52
...                             ...   ...                    ...          ...               ...          ...
401013173  2018-11-10T20:30:00.000Z    11          Virginia Tech           22        Pittsburgh           52
401015042  2018-11-10T20:30:00.000Z    11            North Texas           31      Old Dominion           34
401012331  2018-11-10T20:30:00.000Z    11      Mississippi State            0           Alabama           24
401013035  2018-11-10T20:30:00.000Z    11                 Baylor           14        Iowa State           28
401013070  2018-11-10T20:30:00.000Z    11         Oklahoma State           47          Oklahoma           48
401012336  2018-11-10T20:30:00.000Z    11               Kentucky            7         Tennessee           24
401019526  2018-11-10T21:00:00.000Z    11          East Carolina           18            Tulane           24
401021702  2018-11-10T21:00:00.000Z    11      Appalachian State           38       Texas State            7
401022557  2018-11-10T21:00:00.000Z    11         San José State           24        Utah State           62
401015039  2018-11-10T22:00:00.000Z    11       Western Kentucky           15  Florida Atlantic           34
401021688  2018-11-10T22:00:00.000Z    11         Arkansas State           44  Coastal Carolina           16
401021691  2018-11-10T22:00:00.000Z    11       Louisiana Monroe           38     South Alabama           10
401021690  2018-11-10T22:00:00.000Z    11          Georgia State           22         Louisiana           36
401012789  2018-11-10T22:30:00.000Z    11                 Oregon           25              Utah           32
401015038  2018-11-11T00:00:00.000Z    11  Florida International           45    UT San Antonio            7
401019527  2018-11-11T00:00:00.000Z    11                 Temple           59           Houston           49
401019524  2018-11-11T00:00:00.000Z    11          South Florida           23        Cincinnati           35
401013172  2018-11-11T00:00:00.000Z    11                  Miami           21      Georgia Tech           27
401015040  2018-11-11T00:00:00.000Z    11                   Rice           13    Louisiana Tech           28
401012334  2018-11-11T00:00:00.000Z    11                 Auburn           10           Georgia           27
401013321  2018-11-11T00:30:00.000Z    11                  Texas           41        Texas Tech           34
401013171  2018-11-11T00:30:00.000Z    11          Florida State           13        Notre Dame           42
401015043  2018-11-11T00:30:00.000Z    11   Southern Mississippi           23               UAB           26
401012332  2018-11-11T00:30:00.000Z    11                    LSU           24          Arkansas           17
401013169  2018-11-11T01:00:00.000Z    11                Clemson           27    Boston College            7
401012790  2018-11-11T02:00:00.000Z    11           Oregon State           17          Stanford           48
401012787  2018-11-11T03:30:00.000Z    11             California           15               USC           14
401022558  2018-11-11T03:30:00.000Z    11                   UNLV           27   San Diego State           24
401022555  2018-11-11T03:30:00.000Z    11         Colorado State           10            Nevada           49
401020780  2018-11-13T23:00:00.000Z    12       Western Michigan           41        Ball State           42

[595 rows x 6 columns]

In [3]:
for index, row in df.iterrows():
    sd = row["start_date"]
    year = sd.split("-")[0]
    month = sd.split("-")[1]
    day = sd.split("-")[2][:2]
    
    df.at[index, "start_date"] = year+month+day
df

          start_date  week              away_team  away_points         home_team  home_points
game_id
401022510   20180825     1                Hawai'i           43    Colorado State           34
401013437   20180826     1                Wyoming           29  New Mexico State            7
401013328   20180830     1       New Mexico State           10         Minnesota           48
401019470   20180830     1                    UCF           56       Connecticut           17
401013086   20180831     1            Wake Forest           23            Tulane           17
401013342   20180831     1           Northwestern           31            Purdue           27
401020673   20180831     1               Syracuse           55  Western Michigan           42
401012880   20180831     1             Utah State           31    Michigan State           38
401013089   20180831     1                   Army           14              Duke           34
401022512   20180901     1        San Diego State           10          Stanford           31
401013354   20180901     1       Western Kentucky            3         Wisconsin           34
401012680   20180901     1               Colorado           45    Colorado State           13
401012820   20180901     1            Texas State            7           Rutgers           35
401013065   20180901     1       Florida Atlantic           14          Oklahoma           63
401012804   20180901     1             Kent State           24          Illinois           31
401012872   20180901     1                  Texas           29          Maryland           34
401012256   20180901     1       Coastal Carolina           15    South Carolina           49
401014977   20180901     1                Houston           45              Rice           27
401012253   20180901     1               Ole Miss           47        Texas Tech           27
401012682   20180901     1           Oregon State           31        Ohio State           77
401013087   20180901     1                  UMass           21    Boston College           55
401013349   20180901     1      Appalachian State           38        Penn State           45
401012683   20180901     1       Washington State           41           Wyoming           19
401012257   20180901     1          West Virginia           40         Tennessee           14
401012248   20180901     1             Washington           16            Auburn           21
401012251   20180901     1       Central Michigan           20          Kentucky           35
401012862   20180901     1      Northern Illinois            7              Iowa           33
401012684   20180901     1         North Carolina           17        California           24
401012678   20180901     1                   UNLV           21               USC           43
401013448   20180901     1           Old Dominion           10           Liberty           52
...              ...   ...                    ...          ...               ...          ...
401013173   20181110    11          Virginia Tech           22        Pittsburgh           52
401015042   20181110    11            North Texas           31      Old Dominion           34
401012331   20181110    11      Mississippi State            0           Alabama           24
401013035   20181110    11                 Baylor           14        Iowa State           28
401013070   20181110    11         Oklahoma State           47          Oklahoma           48
401012336   20181110    11               Kentucky            7         Tennessee           24
401019526   20181110    11          East Carolina           18            Tulane           24
401021702   20181110    11      Appalachian State           38       Texas State            7
401022557   20181110    11         San José State           24        Utah State           62
401015039   20181110    11       Western Kentucky           15  Florida Atlantic           34
401021688   20181110    11         Arkansas State           44  Coastal Carolina           16
401021691   20181110    11       Louisiana Monroe           38     South Alabama           10
401021690   20181110    11          Georgia State           22         Louisiana           36
401012789   20181110    11                 Oregon           25              Utah           32
401015038   20181111    11  Florida International           45    UT San Antonio            7
401019527   20181111    11                 Temple           59           Houston           49
401019524   20181111    11          South Florida           23        Cincinnati           35
401013172   20181111    11                  Miami           21      Georgia Tech           27
401015040   20181111    11                   Rice           13    Louisiana Tech           28
401012334   20181111    11                 Auburn           10           Georgia           27
401013321   20181111    11                  Texas           41        Texas Tech           34
401013171   20181111    11          Florida State           13        Notre Dame           42
401015043   20181111    11   Southern Mississippi           23               UAB           26
401012332   20181111    11                    LSU           24          Arkansas           17
401013169   20181111    11                Clemson           27    Boston College            7
401012790   20181111    11           Oregon State           17          Stanford           48
401012787   20181111    11             California           15               USC           14
401022558   20181111    11                   UNLV           27   San Diego State           24
401022555   20181111    11         Colorado State           10            Nevada           49
401020780   20181113    12       Western Michigan           41        Ball State           42

[595 rows x 6 columns]

In [4]:
import lineData
from aPPD import predictGames
import numpy as np

def simulateWeek(week, betThreshold):
    week_df = df[df.week == week].copy()
    
    week_df["prediction_noHFA"] = predictGames((week_df.away_team, week_df.home_team), season=SEASON, weekThrough=week-1)
    week_df = week_df[week_df.prediction_noHFA != -999]
    week_df = week_df.round(2)
    
    days = week_df.start_date.unique()
    firstDay = int(days[0]) - 1
    lastDay = int(days[-1]) + 1
    
    lines_df = pd.DataFrame()
    for date in range(firstDay, lastDay+1):
        day = int(str(date)[-2:])
        if day <= 31 and day > 0:
            #print(date)
            lines_df = lines_df.append(lineData.getSpreads(str(date)), ignore_index=True)
        else:
            pass
    
    week_df = pd.merge(week_df, lines_df, how="left", on=["away_team", "home_team"])
    week_df = week_df[week_df.opening_line != "N/A"]
    
    week_df.loc[week_df.opening_line == "PK", "opening_line"] = 0
    
    week_df["bet_ats"] = None
    week_df["bet_su"] = None
    
    for index, row in week_df.iterrows():
        if row["prediction_noHFA"] - float(row["opening_line"]) >= (betThreshold + HFA):
            week_df.at[index, "bet_ats"] = row["away_team"]
        elif row["prediction_noHFA"] - float(row["opening_line"]) <= -1*betThreshold:
            week_df.at[index, "bet_ats"] = row["home_team"]
    
    for index, row in week_df.iterrows():
        if row["prediction_noHFA"] >= betThreshold:
            week_df.at[index, "bet_su"] = row["away_team"]
        elif row["prediction_noHFA"] <= -1*betThreshold:
            week_df.at[index, "bet_su"] = row["home_team"]
    
    week_df["result"] = week_df["away_points"] - week_df["home_points"]
    
    week_df["win_ats"] = np.nan
    week_df.loc[week_df.bet_ats.notnull(), "win_ats"] = 0
    week_df["win_su"] = np.nan
    week_df.loc[week_df.bet_su.notnull(), "win_su"] = 0
    
    for index, row in week_df.iterrows():
        if row["bet_ats"]:
            if str(row["result"]) == row["opening_line"]:  # push
                week_df.at[index, "win_ats"] = np.nan
            elif row["result"] > float(row["opening_line"]):  # road team wins
                if row["bet_ats"] == row["away_team"]:
                    week_df.at[index, "win_ats"] = 1
            elif row["result"] < float(row["opening_line"]):  # home team wins
                if row["bet_ats"] == row["home_team"]:
                    week_df.at[index, "win_ats"] = 1
    
    for index, row in week_df.iterrows():
        if row["bet_su"]:
            if row["result"] > 0:  # road team wins
                if row["bet_su"] == row["away_team"]:
                    week_df.at[index, "win_su"] = 1
            elif row["result"] < 0:  # home team wins
                if row["bet_su"] == row["home_team"]:
                    week_df.at[index, "win_su"] = 1
    
    metrics = {
        "ats_wins": len(week_df[week_df.win_ats == 1]),
        "ats_losses": len(week_df[week_df.win_ats == 0]),
        "ats_acc": np.nanmean(week_df.win_ats),
        
        "su_wins": len(week_df[week_df.win_su == 1]),
        "su_losses": len(week_df[week_df.win_su == 0]),
        "su_acc": np.nanmean(week_df.win_su)
    }
  
    return week_df, metrics

In [5]:
#week_df, metrics = simulateWeek(7, BET_THRESHOLD)
#print(metrics)

In [6]:
season_df = pd.DataFrame()

ats_wins = 0
ats_losses = 0
su_wins = 0
su_losses = 0
for w in range(START_BETTING, END_BETTING+1):
    print("WEEK %d:" % w)
    week_df, week_metrics = simulateWeek(w, BET_THRESHOLD)
    print(week_metrics)
    print()
    
    ats_wins += week_metrics["ats_wins"]
    ats_losses += week_metrics["ats_losses"]
    
    su_wins += week_metrics["su_wins"]
    su_losses += week_metrics["su_losses"]
    
    season_df = pd.concat([season_df, week_df], sort=False)

season_df

WEEK 5:
{'ats_wins': 20, 'ats_losses': 28, 'ats_acc': 0.4166666666666667, 'su_wins': 35, 'su_losses': 20, 'su_acc': 0.6363636363636364}

WEEK 6:
{'ats_wins': 27, 'ats_losses': 17, 'ats_acc': 0.6136363636363636, 'su_wins': 36, 'su_losses': 17, 'su_acc': 0.6792452830188679}

WEEK 7:
{'ats_wins': 27, 'ats_losses': 24, 'ats_acc': 0.5294117647058824, 'su_wins': 39, 'su_losses': 13, 'su_acc': 0.75}

WEEK 8:
{'ats_wins': 20, 'ats_losses': 25, 'ats_acc': 0.4444444444444444, 'su_wins': 46, 'su_losses': 7, 'su_acc': 0.8679245283018868}

WEEK 9:
{'ats_wins': 23, 'ats_losses': 22, 'ats_acc': 0.5111111111111111, 'su_wins': 33, 'su_losses': 20, 'su_acc': 0.6226415094339622}

WEEK 10:
{'ats_wins': 32, 'ats_losses': 17, 'ats_acc': 0.6530612244897959, 'su_wins': 45, 'su_losses': 14, 'su_acc': 0.7627118644067796}

WEEK 11:
{'ats_wins': 18, 'ats_losses': 30, 'ats_acc': 0.375, 'su_wins': 48, 'su_losses': 13, 'su_acc': 0.7868852459016393}

   start_date  week              away_team  away_points          home_team  home_points  prediction_noHFA opening_line                bet_ats                 bet_su  result  win_ats  win_su
0    20180928     5         North Carolina           10              Miami           47            -18.13        -19.5                   None                  Miami     -37      NaN     1.0
1    20180929     5                Memphis           24             Tulane           40             32.38        +13.5                Memphis                Memphis     -16      0.0     0.0
2    20180929     5                   UCLA           16           Colorado           38            -19.49          -11               Colorado               Colorado     -22      1.0     1.0
3    20180929     5          West Virginia           42         Texas Tech           34              3.08           +5             Texas Tech          West Virginia       8      0.0     1.0
4    20180929     5                   Army           42            Buffalo           13             -3.09           -6                   None                Buffalo      29      NaN     0.0
5    20180929     5       Central Michigan           20     Michigan State           31            -26.39          -28                   None         Michigan State     -11      NaN     1.0
6    20180929     5                Indiana           24            Rutgers           17             25.72          +15                Indiana                Indiana       7      0.0     1.0
7    20180929     5               Arkansas           17          Texas A&M           24            -23.76          -17              Texas A&M              Texas A&M      -7      0.0     1.0
8    20180929     5         Oklahoma State           48             Kansas           28             13.51          +17                 Kansas         Oklahoma State      20      0.0     1.0
9    20180929     5               Syracuse           23            Clemson           27            -54.38          -21                Clemson                Clemson      -4      0.0     1.0
10   20180929     5              Louisiana           14            Alabama           56            -77.10        -49.5                Alabama                Alabama     -42      0.0     1.0
11   20180929     5          Bowling Green           17       Georgia Tech           63            -29.77        -25.5           Georgia Tech           Georgia Tech     -46      1.0     1.0
12   20180929     5                 Temple           35     Boston College           45             20.02        -14.5                 Temple                 Temple     -10      1.0     0.0
13   20180929     5               Virginia           21           NC State           35              6.37         -7.5               Virginia               Virginia     -14      0.0     0.0
14   20180929     5                  UMass           42               Ohio           58            -33.33          -14                   Ohio                   Ohio     -16      1.0     1.0
15   20180929     5       Louisiana Monroe           14      Georgia State           46             19.07         +7.5       Louisiana Monroe       Louisiana Monroe     -32      0.0     0.0
16   20180929     5             Kent State           24         Ball State           52             -1.07         -7.5             Kent State             Ball State     -28      0.0     1.0
17   20180929     5           Old Dominion           35      East Carolina           37            -37.70         -6.5          East Carolina          East Carolina      -2      0.0     1.0
18   20180929     5             Cincinnati           49        Connecticut            7             38.13          +17             Cincinnati             Cincinnati      42      1.0     1.0
19   20180929     5              Tennessee           12            Georgia           38            -45.76        -32.5                Georgia                Georgia     -26      0.0     1.0
20   20180929     5       Coastal Carolina           21               Troy           45            -13.12          -15                   None                   Troy     -24      NaN     1.0
21   20180929     5       Western Michigan           40         Miami (OH)           39             -6.36           -3             Miami (OH)             Miami (OH)       1      0.0     0.0
22   20180929     5             Pittsburgh           14                UCF           45             -5.14        -14.5             Pittsburgh                    UCF     -31      0.0     1.0
23   20180929     5                  Texas           19       Kansas State           14             15.65           +7                  Texas                  Texas       5      0.0     1.0
24   20180929     5                 Purdue           42           Nebraska           28             37.20           +3                 Purdue                 Purdue      14      1.0     1.0
25   20180929     5                 Baylor           33           Oklahoma           66            -12.55        -21.5                 Baylor               Oklahoma     -33      0.0     1.0
26   20180929     5                   Rice           24        Wake Forest           56              2.29        -24.5                   Rice                   Rice     -32      0.0     0.0
27   20180929     5          South Alabama            7  Appalachian State           52            -30.42          -23      Appalachian State      Appalachian State     -45      1.0     1.0
28   20180929     5          Florida State           28         Louisville           24            -18.75         +5.5             Louisville             Louisville       4      1.0     0.0
29   20180929     5   Southern Mississippi           13             Auburn           24            -14.34        -29.5   Southern Mississippi                 Auburn     -11      1.0     1.0
..        ...   ...                    ...          ...                ...          ...               ...          ...                    ...                    ...     ...      ...     ...
31   20181110    11             New Mexico           24          Air Force           42             -5.70        -13.5             New Mexico              Air Force     -18      0.0     1.0
32   20181110    11          Virginia Tech           22         Pittsburgh           52             -7.03         -3.5             Pittsburgh             Pittsburgh     -30      1.0     1.0
33   20181110    11            North Texas           31       Old Dominion           34             28.62        +14.5            North Texas            North Texas      -3      0.0     0.0
34   20181110    11      Mississippi State            0            Alabama           24            -15.32          -24      Mississippi State                Alabama     -24      NaN     1.0
35   20181110    11                 Baylor           14         Iowa State           28            -14.11          -14                   None             Iowa State     -14      NaN     1.0
36   20181110    11         Oklahoma State           47           Oklahoma           48            -23.57        -17.5               Oklahoma               Oklahoma      -1      0.0     1.0
37   20181110    11               Kentucky            7          Tennessee           24             13.12         +3.5               Kentucky               Kentucky     -17      0.0     0.0
38   20181110    11          East Carolina           18             Tulane           24            -11.13        -14.5          East Carolina                 Tulane      -6      1.0     1.0
39   20181110    11      Appalachian State           38        Texas State            7             24.80        +21.5      Appalachian State      Appalachian State      31      1.0     1.0
40   20181110    11         San José State           24         Utah State           62            -33.28        -29.5             Utah State             Utah State     -38      1.0     1.0
41   20181110    11       Western Kentucky           15   Florida Atlantic           34            -16.45          -18                   None       Florida Atlantic     -19      NaN     1.0
42   20181110    11         Arkansas State           44   Coastal Carolina           16              3.87         +6.5       Coastal Carolina         Arkansas State      28      0.0     1.0
43   20181110    11       Louisiana Monroe           38      South Alabama           10              9.34         +4.5       Louisiana Monroe       Louisiana Monroe      28      1.0     1.0
44   20181110    11          Georgia State           22          Louisiana           36            -11.62          -13                   None              Louisiana     -14      NaN     1.0
45   20181110    11                 Oregon           25               Utah           32            -10.01         -3.5                   Utah                   Utah      -7      1.0     1.0
46   20181111    11  Florida International           45     UT San Antonio            7             17.77        +10.5  Florida International  Florida International      38      1.0     1.0
47   20181111    11                 Temple           59            Houston           49              7.19           -4                 Temple                 Temple      10      1.0     1.0
48   20181111    11          South Florida           23         Cincinnati           35            -18.27          -12             Cincinnati             Cincinnati     -12      NaN     1.0
49   20181111    11                  Miami           21       Georgia Tech           27             10.07         -4.5                  Miami                  Miami      -6      0.0     0.0
50   20181111    11                   Rice           13     Louisiana Tech           28            -27.00          -25         Louisiana Tech         Louisiana Tech     -15      0.0     1.0
51   20181111    11                 Auburn           10            Georgia           27            -23.72        -14.5                Georgia                Georgia     -17      1.0     1.0
52   20181111    11                  Texas           41         Texas Tech           34              0.75           -1                   None                  Texas       7      NaN     1.0
53   20181111    11          Florida State           13         Notre Dame           42            -20.91          -18             Notre Dame             Notre Dame     -29      1.0     1.0
54   20181111    11   Southern Mississippi           23                UAB           26            -12.39        -11.5                    UAB                    UAB      -3      0.0     1.0
55   20181111    11                    LSU           24           Arkansas           17             23.26          +14                    LSU                    LSU       7      0.0     1.0
56   20181111    11                Clemson           27     Boston College            7             22.02        +17.5                Clemson                Clemson      20      1.0     1.0
57   20181111    11           Oregon State           17           Stanford           48            -25.28        -22.5               Stanford               Stanford     -31      1.0     1.0
58   20181111    11             California           15                USC           14             -7.13           -5                    USC                    USC       1      0.0     0.0
59   20181111    11                   UNLV           27    San Diego State           24            -20.56          -18        San Diego State        San Diego State       3      0.0     0.0
60   20181111    11         Colorado State           10             Nevada           49             -3.96          -13         Colorado State                 Nevada     -39      0.0     1.0

[396 rows x 13 columns]

In [7]:
print("ATS:")
print(ats_wins, "/", str(ats_losses + ats_wins))
print(ats_wins / (ats_losses + ats_wins))
print()

print("SU:")
print(su_wins, "/", str(su_losses + su_wins))
print(su_wins / (su_losses + su_wins))

ATS:
167 / 330
0.5060606060606061

SU:
282 / 386
0.7305699481865285