In [1]:
season = 2018
weekThrough = 10

startBetting = 5

In [2]:
import pandas as pd

df = pd.read_json("Data/allgames" + str(season) + ".json")
df["fbsonly"] = "no"
for index, row in df.iterrows():
    if row["home_conference"] != None and row["away_conference"] != None:
        df.at[index, "fbsonly"] = "yes"

df = df[df.fbsonly == "yes"]
df = df.set_index("id")
df = df[["start_date", "away_team", "away_points", "home_team", "home_points"]]

df = df.copy()
df

,start_date,away_team,away_points,home_team,home_points
id,,,,,
401022510,2018-08-25T23:30:00.000Z,Hawai'i,43,Colorado State,34
401013437,2018-08-26T02:00:00.000Z,Wyoming,29,New Mexico State,7
401019470,2018-08-30T23:00:00.000Z,UCF,56,Connecticut,17
401013328,2018-08-30T23:00:00.000Z,New Mexico State,10,Minnesota,48
401013086,2018-08-31T00:00:00.000Z,Wake Forest,23,Tulane,17
401013342,2018-08-31T00:00:00.000Z,Northwestern,31,Purdue,27
401020673,2018-08-31T22:00:00.000Z,Syracuse,55,Western Michigan,42
401012880,2018-08-31T23:00:00.000Z,Utah State,31,Michigan State,38
401013089,2018-08-31T23:00:00.000Z,Army,14,Duke,34
401022512,2018-09-01T01:00:00.000Z,San Diego State,10,Stanford,31
401013354,2018-09-01T01:00:00.000Z,Western Kentucky,3,Wisconsin,34
401012680,2018-09-01T01:30:00.000Z,Colorado,45,Colorado State,13
401012872,2018-09-01T16:00:00.000Z,Texas,29,Maryland,34
401012256,2018-09-01T16:00:00.000Z,Coastal Carolina,15,South Carolina,49
401012820,2018-09-01T16:00:00.000Z,Texas State,7,Rutgers,35
401013065,2018-09-01T16:00:00.000Z,Florida Atlantic,14,Oklahoma,63
401012804,2018-09-01T16:00:00.000Z,Kent State,24,Illinois,31
401014977,2018-09-01T16:00:00.000Z,Houston,45,Rice,27
401012253,2018-09-01T16:00:00.000Z,Ole Miss,47,Texas Tech,27
401012682,2018-09-01T16:00:00.000Z,Oregon State,31,Ohio State,77
401013087,2018-09-01T17:00:00.000Z,UMass,21,Boston College,55
401012257,2018-09-01T19:30:00.000Z,West Virginia,40,Tennessee,14
401012248,2018-09-01T19:30:00.000Z,Washington,16,Auburn,21
401013349,2018-09-01T19:30:00.000Z,Appalachian State,38,Penn State,45
401012683,2018-09-01T19:30:00.000Z,Washington State,41,Wyoming,19
401012251,2018-09-01T19:30:00.000Z,Central Michigan,20,Kentucky,35
401012862,2018-09-01T19:40:00.000Z,Northern Illinois,7,Iowa,33
401012678,2018-09-01T20:00:00.000Z,UNLV,21,USC,43
401012684,2018-09-01T20:00:00.000Z,North Carolina,17,California,24
401013448,2018-09-01T22:00:00.000Z,Old Dominion,10,Liberty,52
...,...,...,...,...,...
401013188,2018-11-03T19:30:00.000Z,West Virginia,42,Texas,41
401019521,2018-11-03T19:30:00.000Z,Tulane,41,South Florida,15
401021687,2018-11-03T19:30:00.000Z,Louisiana,16,Troy,26
401015035,2018-11-03T19:30:00.000Z,UTEP,34,Rice,26
401019518,2018-11-03T19:30:00.000Z,Navy,0,Cincinnati,42
401013164,2018-11-03T19:30:00.000Z,Florida State,28,NC State,47
401012812,2018-11-03T19:30:00.000Z,Minnesota,31,Illinois,55
401013161,2018-11-03T19:45:00.000Z,Boston College,31,Virginia Tech,21
401012894,2018-11-03T19:45:00.000Z,Penn State,7,Michigan,42
401012325,2018-11-03T20:00:00.000Z,Missouri,38,Florida,17
401012330,2018-11-03T20:00:00.000Z,Charlotte,3,Tennessee,14
401012781,2018-11-03T20:00:00.000Z,Utah,20,Arizona State,38
401021683,2018-11-03T21:00:00.000Z,Appalachian State,23,Coastal Carolina,7
401013163,2018-11-03T23:00:00.000Z,Duke,20,Miami,12
401019522,2018-11-03T23:00:00.000Z,Houston,31,SMU,45
401019519,2018-11-03T23:00:00.000Z,Connecticut,19,Tulsa,49
401013345,2018-11-03T23:15:00.000Z,Notre Dame,31,Northwestern,21
401012782,2018-11-03T23:30:00.000Z,UCLA,21,Oregon,42
401012329,2018-11-03T23:30:00.000Z,Louisiana Tech,3,Mississippi State,45
401015032,2018-11-03T23:30:00.000Z,Florida Atlantic,49,Florida International,14
401015036,2018-11-03T23:30:00.000Z,UT San Antonio,3,UAB,52
401013069,2018-11-04T00:00:00.000Z,Oklahoma,51,Texas Tech,46
401012327,2018-11-04T00:00:00.000Z,Alabama,29,LSU,0
401012784,2018-11-04T01:00:00.000Z,Stanford,23,Washington,27
401012783,2018-11-04T02:00:00.000Z,USC,38,Oregon State,21
401022550,2018-11-04T02:15:00.000Z,San Diego State,31,New Mexico,23
401016410,2018-11-04T02:15:00.000Z,BYU,16,Boise State,21
401022553,2018-11-04T02:30:00.000Z,Fresno State,48,UNLV,3
401012785,2018-11-04T02:45:00.000Z,California,13,Washington State,19
401022551,2018-11-04T03:59:00.000Z,Utah State,56,Hawai'i,17

In [3]:
for index, row in df.iterrows():
    sd = row["start_date"]
    year = sd.split("-")[0]
    month = sd.split("-")[1]
    day = sd.split("-")[2][:2]
    
    df.at[index, "start_date"] = year+month+day
df

,start_date,away_team,away_points,home_team,home_points
id,,,,,
401022510,20180825,Hawai'i,43,Colorado State,34
401013437,20180826,Wyoming,29,New Mexico State,7
401019470,20180830,UCF,56,Connecticut,17
401013328,20180830,New Mexico State,10,Minnesota,48
401013086,20180831,Wake Forest,23,Tulane,17
401013342,20180831,Northwestern,31,Purdue,27
401020673,20180831,Syracuse,55,Western Michigan,42
401012880,20180831,Utah State,31,Michigan State,38
401013089,20180831,Army,14,Duke,34
401022512,20180901,San Diego State,10,Stanford,31
401013354,20180901,Western Kentucky,3,Wisconsin,34
401012680,20180901,Colorado,45,Colorado State,13
401012872,20180901,Texas,29,Maryland,34
401012256,20180901,Coastal Carolina,15,South Carolina,49
401012820,20180901,Texas State,7,Rutgers,35
401013065,20180901,Florida Atlantic,14,Oklahoma,63
401012804,20180901,Kent State,24,Illinois,31
401014977,20180901,Houston,45,Rice,27
401012253,20180901,Ole Miss,47,Texas Tech,27
401012682,20180901,Oregon State,31,Ohio State,77
401013087,20180901,UMass,21,Boston College,55
401012257,20180901,West Virginia,40,Tennessee,14
401012248,20180901,Washington,16,Auburn,21
401013349,20180901,Appalachian State,38,Penn State,45
401012683,20180901,Washington State,41,Wyoming,19
401012251,20180901,Central Michigan,20,Kentucky,35
401012862,20180901,Northern Illinois,7,Iowa,33
401012678,20180901,UNLV,21,USC,43
401012684,20180901,North Carolina,17,California,24
401013448,20180901,Old Dominion,10,Liberty,52
...,...,...,...,...,...
401013188,20181103,West Virginia,42,Texas,41
401019521,20181103,Tulane,41,South Florida,15
401021687,20181103,Louisiana,16,Troy,26
401015035,20181103,UTEP,34,Rice,26
401019518,20181103,Navy,0,Cincinnati,42
401013164,20181103,Florida State,28,NC State,47
401012812,20181103,Minnesota,31,Illinois,55
401013161,20181103,Boston College,31,Virginia Tech,21
401012894,20181103,Penn State,7,Michigan,42
401012325,20181103,Missouri,38,Florida,17
401012330,20181103,Charlotte,3,Tennessee,14
401012781,20181103,Utah,20,Arizona State,38
401021683,20181103,Appalachian State,23,Coastal Carolina,7
401013163,20181103,Duke,20,Miami,12
401019522,20181103,Houston,31,SMU,45
401019519,20181103,Connecticut,19,Tulsa,49
401013345,20181103,Notre Dame,31,Northwestern,21
401012782,20181103,UCLA,21,Oregon,42
401012329,20181103,Louisiana Tech,3,Mississippi State,45
401015032,20181103,Florida Atlantic,49,Florida International,14
401015036,20181103,UT San Antonio,3,UAB,52
401013069,20181104,Oklahoma,51,Texas Tech,46
401012327,20181104,Alabama,29,LSU,0
401012784,20181104,Stanford,23,Washington,27
401012783,20181104,USC,38,Oregon State,21
401022550,20181104,San Diego State,31,New Mexico,23
401016410,20181104,BYU,16,Boise State,21
401022553,20181104,Fresno State,48,UNLV,3
401012785,20181104,California,13,Washington State,19
401022551,20181104,Utah State,56,Hawai'i,17

In [ ]:
# convert game predictor to module
# convert aPPD calculator to module