In [1]:
SEASON = 2018

START_BETTING = 4
END_BETTING = 10

BET_THRESHOLD = 0.1
HFA = 2.5

In [2]:
import pandas as pd

pd.set_option('display.max_columns', 500)  # prints the df properly in console instead of splitting up columns
pd.set_option('display.width', 1000)

df = pd.read_json("https://api.collegefootballdata.com/games?year=" + str(SEASON))
df = df[(df.away_conference.notnull()) & (df.home_conference.notnull())]
df = df[["id", "start_date", "week", "away_team", "away_points", "home_team", "home_points"]]
df = df.set_index("id")
df.index = df.index.rename("game_id")
df

                         start_date  week          away_team  away_points              home_team  home_points
game_id
401022510  2018-08-25T23:30:00.000Z     1            Hawai'i           43         Colorado State           34
401013437  2018-08-26T02:00:00.000Z     1            Wyoming           29       New Mexico State            7
401019470  2018-08-30T23:00:00.000Z     1                UCF           56            Connecticut           17
401013328  2018-08-30T23:00:00.000Z     1   New Mexico State           10              Minnesota           48
401013086  2018-08-31T00:00:00.000Z     1        Wake Forest           23                 Tulane           17
401013342  2018-08-31T00:00:00.000Z     1       Northwestern           31                 Purdue           27
401020673  2018-08-31T22:00:00.000Z     1           Syracuse           55       Western Michigan           42
401012880  2018-08-31T23:00:00.000Z     1         Utah State           31         Michigan State           38
401013089  2018-08-31T23:00:00.000Z     1               Army           14                   Duke           34
401022512  2018-09-01T01:00:00.000Z     1    San Diego State           10               Stanford           31
401013354  2018-09-01T01:00:00.000Z     1   Western Kentucky            3              Wisconsin           34
401012680  2018-09-01T01:30:00.000Z     1           Colorado           45         Colorado State           13
401012872  2018-09-01T16:00:00.000Z     1              Texas           29               Maryland           34
401012256  2018-09-01T16:00:00.000Z     1   Coastal Carolina           15         South Carolina           49
401012820  2018-09-01T16:00:00.000Z     1        Texas State            7                Rutgers           35
401013065  2018-09-01T16:00:00.000Z     1   Florida Atlantic           14               Oklahoma           63
401012804  2018-09-01T16:00:00.000Z     1         Kent State           24               Illinois           31
401014977  2018-09-01T16:00:00.000Z     1            Houston           45                   Rice           27
401012253  2018-09-01T16:00:00.000Z     1           Ole Miss           47             Texas Tech           27
401012682  2018-09-01T16:00:00.000Z     1       Oregon State           31             Ohio State           77
401013087  2018-09-01T17:00:00.000Z     1              UMass           21         Boston College           55
401012257  2018-09-01T19:30:00.000Z     1      West Virginia           40              Tennessee           14
401012248  2018-09-01T19:30:00.000Z     1         Washington           16                 Auburn           21
401013349  2018-09-01T19:30:00.000Z     1  Appalachian State           38             Penn State           45
401012683  2018-09-01T19:30:00.000Z     1   Washington State           41                Wyoming           19
401012251  2018-09-01T19:30:00.000Z     1   Central Michigan           20               Kentucky           35
401012862  2018-09-01T19:40:00.000Z     1  Northern Illinois            7                   Iowa           33
401012678  2018-09-01T20:00:00.000Z     1               UNLV           21                    USC           43
401012684  2018-09-01T20:00:00.000Z     1     North Carolina           17             California           24
401013448  2018-09-01T22:00:00.000Z     1       Old Dominion           10                Liberty           52
...                             ...   ...                ...          ...                    ...          ...
401013188  2018-11-03T19:30:00.000Z    10      West Virginia           42                  Texas           41
401012894  2018-11-03T19:45:00.000Z    10         Penn State            7               Michigan           42
401013161  2018-11-03T19:45:00.000Z    10     Boston College           31          Virginia Tech           21
401012325  2018-11-03T20:00:00.000Z    10           Missouri           38                Florida           17
401012781  2018-11-03T20:00:00.000Z    10               Utah           20          Arizona State           38
401012330  2018-11-03T20:00:00.000Z    10          Charlotte            3              Tennessee           14
401021683  2018-11-03T21:00:00.000Z    10  Appalachian State           23       Coastal Carolina            7
401019519  2018-11-03T23:00:00.000Z    10        Connecticut           19                  Tulsa           49
401019522  2018-11-03T23:00:00.000Z    10            Houston           31                    SMU           45
401013163  2018-11-03T23:00:00.000Z    10               Duke           20                  Miami           12
401013345  2018-11-03T23:15:00.000Z    10         Notre Dame           31           Northwestern           21
401012329  2018-11-03T23:30:00.000Z    10     Louisiana Tech            3      Mississippi State           45
401015036  2018-11-03T23:30:00.000Z    10     UT San Antonio            3                    UAB           52
401012782  2018-11-03T23:30:00.000Z    10               UCLA           21                 Oregon           42
401015032  2018-11-03T23:30:00.000Z    10   Florida Atlantic           49  Florida International           14
401012327  2018-11-04T00:00:00.000Z    10            Alabama           29                    LSU            0
401013069  2018-11-04T00:00:00.000Z    10           Oklahoma           51             Texas Tech           46
401012784  2018-11-04T01:00:00.000Z    10           Stanford           23             Washington           27
401012783  2018-11-04T02:00:00.000Z    10                USC           38           Oregon State           21
401016410  2018-11-04T02:15:00.000Z    10                BYU           16            Boise State           21
401022550  2018-11-04T02:15:00.000Z    10    San Diego State           31             New Mexico           23
401022553  2018-11-04T02:30:00.000Z    10       Fresno State           48                   UNLV            3
401012785  2018-11-04T02:45:00.000Z    10         California           13       Washington State           19
401022551  2018-11-04T03:59:00.000Z    10         Utah State           56                Hawai'i           17
401020775  2018-11-07T00:30:00.000Z    11         Kent State           14                Buffalo           48
401020776  2018-11-08T00:00:00.000Z    11               Ohio           28             Miami (OH)           30
401020777  2018-11-08T01:00:00.000Z    11             Toledo           15      Northern Illinois           38
401013167  2018-11-09T00:30:00.000Z    11        Wake Forest           27               NC State           23
401013168  2018-11-10T00:00:00.000Z    11         Louisville           23               Syracuse           54
401022556  2018-11-10T03:15:00.000Z    11       Fresno State           17            Boise State           24

[539 rows x 6 columns]

In [3]:
for index, row in df.iterrows():
    sd = row["start_date"]
    year = sd.split("-")[0]
    month = sd.split("-")[1]
    day = sd.split("-")[2][:2]
    
    df.at[index, "start_date"] = year+month+day
df

          start_date  week          away_team  away_points              home_team  home_points
game_id
401022510   20180825     1            Hawai'i           43         Colorado State           34
401013437   20180826     1            Wyoming           29       New Mexico State            7
401019470   20180830     1                UCF           56            Connecticut           17
401013328   20180830     1   New Mexico State           10              Minnesota           48
401013086   20180831     1        Wake Forest           23                 Tulane           17
401013342   20180831     1       Northwestern           31                 Purdue           27
401020673   20180831     1           Syracuse           55       Western Michigan           42
401012880   20180831     1         Utah State           31         Michigan State           38
401013089   20180831     1               Army           14                   Duke           34
401022512   20180901     1    San Diego State           10               Stanford           31
401013354   20180901     1   Western Kentucky            3              Wisconsin           34
401012680   20180901     1           Colorado           45         Colorado State           13
401012872   20180901     1              Texas           29               Maryland           34
401012256   20180901     1   Coastal Carolina           15         South Carolina           49
401012820   20180901     1        Texas State            7                Rutgers           35
401013065   20180901     1   Florida Atlantic           14               Oklahoma           63
401012804   20180901     1         Kent State           24               Illinois           31
401014977   20180901     1            Houston           45                   Rice           27
401012253   20180901     1           Ole Miss           47             Texas Tech           27
401012682   20180901     1       Oregon State           31             Ohio State           77
401013087   20180901     1              UMass           21         Boston College           55
401012257   20180901     1      West Virginia           40              Tennessee           14
401012248   20180901     1         Washington           16                 Auburn           21
401013349   20180901     1  Appalachian State           38             Penn State           45
401012683   20180901     1   Washington State           41                Wyoming           19
401012251   20180901     1   Central Michigan           20               Kentucky           35
401012862   20180901     1  Northern Illinois            7                   Iowa           33
401012678   20180901     1               UNLV           21                    USC           43
401012684   20180901     1     North Carolina           17             California           24
401013448   20180901     1       Old Dominion           10                Liberty           52
...              ...   ...                ...          ...                    ...          ...
401013188   20181103    10      West Virginia           42                  Texas           41
401012894   20181103    10         Penn State            7               Michigan           42
401013161   20181103    10     Boston College           31          Virginia Tech           21
401012325   20181103    10           Missouri           38                Florida           17
401012781   20181103    10               Utah           20          Arizona State           38
401012330   20181103    10          Charlotte            3              Tennessee           14
401021683   20181103    10  Appalachian State           23       Coastal Carolina            7
401019519   20181103    10        Connecticut           19                  Tulsa           49
401019522   20181103    10            Houston           31                    SMU           45
401013163   20181103    10               Duke           20                  Miami           12
401013345   20181103    10         Notre Dame           31           Northwestern           21
401012329   20181103    10     Louisiana Tech            3      Mississippi State           45
401015036   20181103    10     UT San Antonio            3                    UAB           52
401012782   20181103    10               UCLA           21                 Oregon           42
401015032   20181103    10   Florida Atlantic           49  Florida International           14
401012327   20181104    10            Alabama           29                    LSU            0
401013069   20181104    10           Oklahoma           51             Texas Tech           46
401012784   20181104    10           Stanford           23             Washington           27
401012783   20181104    10                USC           38           Oregon State           21
401016410   20181104    10                BYU           16            Boise State           21
401022550   20181104    10    San Diego State           31             New Mexico           23
401022553   20181104    10       Fresno State           48                   UNLV            3
401012785   20181104    10         California           13       Washington State           19
401022551   20181104    10         Utah State           56                Hawai'i           17
401020775   20181107    11         Kent State           14                Buffalo           48
401020776   20181108    11               Ohio           28             Miami (OH)           30
401020777   20181108    11             Toledo           15      Northern Illinois           38
401013167   20181109    11        Wake Forest           27               NC State           23
401013168   20181110    11         Louisville           23               Syracuse           54
401022556   20181110    11       Fresno State           17            Boise State           24

[539 rows x 6 columns]

In [4]:
import lineData
from aPPD import predictGames
import numpy as np

def simulateWeek(week, betThreshold):
    week_df = df[df.week == week].copy()
    
    week_df["prediction_noHFA"] = predictGames((week_df.away_team, week_df.home_team), season=SEASON, weekThrough=week-1)
    week_df = week_df[week_df.prediction_noHFA != -999]
    week_df = week_df.round(2)
    
    days = week_df.start_date.unique()
    firstDay = int(days[0]) - 1
    lastDay = int(days[-1]) + 1
    
    lines_df = pd.DataFrame()
    for date in range(firstDay, lastDay+1):
        day = int(str(date)[-2:])
        if day <= 31 and day > 0:
            #print(date)
            lines_df = lines_df.append(lineData.getLines(str(date)), ignore_index=True)
        else:
            pass
    
    week_df = pd.merge(week_df, lines_df, how="left", on=["away_team", "home_team"])
    week_df = week_df[week_df.opening_line != "N/A"]
    
    week_df.loc[week_df.opening_line == "PK", "opening_line"] = 0
    
    week_df["bet_ats"] = None
    week_df["bet_su"] = None
    
    for index, row in week_df.iterrows():
        if row["prediction_noHFA"] - float(row["opening_line"]) >= (betThreshold + HFA):
            week_df.at[index, "bet_ats"] = row["away_team"]
        elif row["prediction_noHFA"] - float(row["opening_line"]) <= -1*betThreshold:
            week_df.at[index, "bet_ats"] = row["home_team"]
    
    for index, row in week_df.iterrows():
        if row["prediction_noHFA"] >= betThreshold:
            week_df.at[index, "bet_su"] = row["away_team"]
        elif row["prediction_noHFA"] <= -1*betThreshold:
            week_df.at[index, "bet_su"] = row["home_team"]
    
    week_df["result"] = week_df["away_points"] - week_df["home_points"]
    
    week_df["win_ats"] = np.nan
    week_df.loc[week_df.bet_ats.notnull(), "win_ats"] = 0
    week_df["win_su"] = np.nan
    week_df.loc[week_df.bet_su.notnull(), "win_su"] = 0
    
    for index, row in week_df.iterrows():
        if row["bet_ats"]:
            if str(row["result"]) == row["opening_line"]:  # push
                week_df.at[index, "win_ats"] = np.nan
            elif row["result"] > float(row["opening_line"]):  # road team wins
                if row["bet_ats"] == row["away_team"]:
                    week_df.at[index, "win_ats"] = 1
            elif row["result"] < float(row["opening_line"]):  # home team wins
                if row["bet_ats"] == row["home_team"]:
                    week_df.at[index, "win_ats"] = 1
    
    for index, row in week_df.iterrows():
        if row["bet_su"]:
            if row["result"] > 0:  # road team wins
                if row["bet_su"] == row["away_team"]:
                    week_df.at[index, "win_su"] = 1
            elif row["result"] < 0:  # home team wins
                if row["bet_su"] == row["home_team"]:
                    week_df.at[index, "win_su"] = 1
    
    metrics = {
        "ats_wins": len(week_df[week_df.win_ats == 1]),
        "ats_losses": len(week_df[week_df.win_ats == 0]),
        "ats_acc": np.nanmean(week_df.win_ats),
        
        "su_wins": len(week_df[week_df.win_su == 1]),
        "su_losses": len(week_df[week_df.win_su == 0]),
        "su_acc": np.nanmean(week_df.win_su)
    }
  
    return week_df, metrics

In [5]:
#week_df, metrics = simulateWeek(7, BET_THRESHOLD)
#print(metrics)

In [6]:
season_df = pd.DataFrame()

ats_wins = 0
ats_losses = 0
su_wins = 0
su_losses = 0
for w in range(START_BETTING, END_BETTING+1):
    print("WEEK %d:" % w)
    week_df, week_metrics = simulateWeek(w, BET_THRESHOLD)
    print(week_metrics)
    print()
    
    ats_wins += week_metrics["ats_wins"]
    ats_losses += week_metrics["ats_losses"]
    
    su_wins += week_metrics["su_wins"]
    su_losses += week_metrics["su_losses"]
    
    season_df = pd.concat([season_df, week_df], sort=False)

season_df

WEEK 4:
{'ats_wins': 32, 'ats_losses': 22, 'ats_acc': 0.5925925925925926, 'su_wins': 38, 'su_losses': 17, 'su_acc': 0.6909090909090909}

WEEK 5:
{'ats_wins': 20, 'ats_losses': 27, 'ats_acc': 0.425531914893617, 'su_wins': 35, 'su_losses': 20, 'su_acc': 0.6363636363636364}

WEEK 6:
{'ats_wins': 28, 'ats_losses': 18, 'ats_acc': 0.6086956521739131, 'su_wins': 39, 'su_losses': 17, 'su_acc': 0.6964285714285714}

WEEK 7:
{'ats_wins': 27, 'ats_losses': 24, 'ats_acc': 0.5294117647058824, 'su_wins': 38, 'su_losses': 16, 'su_acc': 0.7037037037037037}

WEEK 8:
{'ats_wins': 19, 'ats_losses': 26, 'ats_acc': 0.4222222222222222, 'su_wins': 45, 'su_losses': 9, 'su_acc': 0.8333333333333334}

WEEK 9:
{'ats_wins': 22, 'ats_losses': 25, 'ats_acc': 0.46808510638297873, 'su_wins': 35, 'su_losses': 20, 'su_acc': 0.6363636363636364}

WEEK 10:
{'ats_wins': 28, 'ats_losses': 19, 'ats_acc': 0.5957446808510638, 'su_wins': 46, 'su_losses': 15, 'su_acc': 0.7540983606557377}

   start_date  week              away_team  away_points              home_team  home_points  prediction_noHFA opening_line                bet_ats                 bet_su  result  win_ats  win_su
0    20180920     4                  Tulsa           17                 Temple           31            -27.19         -6.5                 Temple                 Temple     -14      1.0     1.0
1    20180921     4       Florida Atlantic           36                    UCF           56            -47.46        -13.5                    UCF                    UCF     -20      1.0     1.0
2    20180922     4             Penn State           63               Illinois           24             46.28        +26.5             Penn State             Penn State      39      1.0     1.0
3    20180922     4       Washington State           36                    USC           39             23.64         -4.5       Washington State       Washington State      -3      1.0     0.0
4    20180922     4                 Nevada           44                 Toledo           63            -22.36          -10                 Toledo                 Toledo     -19      1.0     1.0
5    20180922     4             Kent State           17               Ole Miss           38            -33.15          -28               Ole Miss               Ole Miss     -21      0.0     1.0
6    20180922     4                Buffalo           42                Rutgers           13             32.26         +3.5                Buffalo                Buffalo      29      1.0     1.0
7    20180922     4                  Akron           13             Iowa State           26             11.15        -19.5                  Akron                  Akron     -13      1.0     0.0
8    20180922     4             Notre Dame           56            Wake Forest           27             45.71           +7             Notre Dame             Notre Dame      29      1.0     1.0
9    20180922     4               Nebraska           10               Michigan           56             -6.63          -18               Nebraska               Michigan     -46      0.0     1.0
10   20180922     4                Georgia           43               Missouri           29             20.37          +14                Georgia                Georgia      14      0.0     1.0
11   20180922     4                   Ohio           30             Cincinnati           34              7.83          -10                   Ohio                   Ohio      -4      1.0     0.0
12   20180922     4                   Navy           30                    SMU           31             -5.64           +7                    SMU                    SMU      -1      1.0     1.0
13   20180922     4         Boston College           13                 Purdue           30            -35.69           +7                 Purdue                 Purdue     -17      1.0     1.0
14   20180922     4              Minnesota           13               Maryland           42             19.89         -1.5              Minnesota              Minnesota     -29      0.0     0.0
15   20180922     4             Pittsburgh           35         North Carolina           38            -25.50         +4.5         North Carolina         North Carolina      -3      1.0     1.0
16   20180922     4             Louisville            3               Virginia           27             -6.79         -3.5               Virginia               Virginia     -24      1.0     1.0
17   20180922     4       Western Michigan           34          Georgia State           15             19.04           +7       Western Michigan       Western Michigan      19      1.0     1.0
18   20180922     4             Miami (OH)           38          Bowling Green           23             38.42         +4.5             Miami (OH)             Miami (OH)      15      1.0     1.0
19   20180922     4       Western Kentucky           28             Ball State           20              2.35         -3.5       Western Kentucky       Western Kentucky       8      1.0     1.0
20   20180922     4                 Kansas            7                 Baylor           26              4.84         -9.5                 Kansas                 Kansas     -19      0.0     0.0
21   20180922     4                Clemson           49           Georgia Tech           21             16.66        +15.5                   None                Clemson      28      NaN     1.0
22   20180922     4              Charlotte           31                  UMass           49             11.24        -10.5              Charlotte              Charlotte     -18      0.0     0.0
23   20180922     4                 Tulane            6             Ohio State           49            -68.62        -34.5             Ohio State             Ohio State     -43      1.0     1.0
24   20180922     4  Florida International           17                  Miami           31            -37.95        -26.5                  Miami                  Miami     -14      0.0     1.0
25   20180922     4           Kansas State            6          West Virginia           35             -2.20          -14           Kansas State          West Virginia     -29      0.0     1.0
26   20180922     4              Texas A&M           23                Alabama           45            -40.06        -23.5                Alabama                Alabama     -22      0.0     1.0
27   20180922     4      Northern Illinois           19          Florida State           37             52.47        -11.5      Northern Illinois      Northern Illinois     -18      0.0     0.0
28   20180922     4          Virginia Tech           35           Old Dominion           49             -4.43          +28           Old Dominion           Old Dominion     -14      1.0     1.0
29   20180922     4            Connecticut           21               Syracuse           51             -1.62        -27.5            Connecticut               Syracuse     -30      0.0     1.0
..        ...   ...                    ...          ...                    ...          ...               ...          ...                    ...                    ...     ...      ...     ...
31   20181103    10           Kansas State           13                    TCU           14             -2.03         -7.5           Kansas State                    TCU      -1      1.0     1.0
32   20181103    10                Georgia           34               Kentucky           17             11.57          +10                   None                Georgia      17      NaN     1.0
33   20181103    10                   Iowa           36                 Purdue           38              5.50         -1.5                   Iowa                   Iowa      -2      0.0     0.0
34   20181103    10                 Tulane           41          South Florida           15              5.03           -8                 Tulane                 Tulane      26      1.0     1.0
35   20181103    10              Minnesota           31               Illinois           55             16.90         +9.5              Minnesota              Minnesota     -24      0.0     0.0
36   20181103    10          Florida State           28               NC State           47            -10.25         -6.5               NC State               NC State     -19      1.0     1.0
37   20181103    10          West Virginia           42                  Texas           41              8.68         -2.5          West Virginia          West Virginia       1      1.0     1.0
38   20181103    10             Penn State            7               Michigan           42             -9.83          -10                   None               Michigan     -35      NaN     1.0
39   20181103    10         Boston College           31          Virginia Tech           21             15.51           +1         Boston College         Boston College      10      1.0     1.0
40   20181103    10               Missouri           38                Florida           17             -6.80           -6                Florida                Florida      21      0.0     0.0
41   20181103    10                   Utah           20          Arizona State           38              9.50           +7                   None                   Utah     -18      NaN     0.0
42   20181103    10              Charlotte            3              Tennessee           14            -24.20          -21              Tennessee              Tennessee     -11      0.0     1.0
43   20181103    10      Appalachian State           23       Coastal Carolina            7             20.96          +14      Appalachian State      Appalachian State      16      1.0     1.0
44   20181103    10            Connecticut           19                  Tulsa           49            -23.54          -17                  Tulsa                  Tulsa     -30      1.0     1.0
45   20181103    10                Houston           31                    SMU           45             16.52          +13                Houston                Houston     -14      0.0     0.0
46   20181103    10                   Duke           20                  Miami           12             -7.96           -7                  Miami                  Miami       8      0.0     0.0
47   20181103    10             Notre Dame           31           Northwestern           21             11.39           +7             Notre Dame             Notre Dame      10      1.0     1.0
48   20181103    10         Louisiana Tech            3      Mississippi State           45            -31.80        -20.5      Mississippi State      Mississippi State     -42      1.0     1.0
49   20181103    10         UT San Antonio            3                    UAB           52            -22.13        -19.5                    UAB                    UAB     -49      1.0     1.0
50   20181103    10                   UCLA           21                 Oregon           42             -0.35          -13                   UCLA                 Oregon     -21      0.0     1.0
51   20181103    10       Florida Atlantic           49  Florida International           14             -9.66           -3  Florida International  Florida International      35      0.0     0.0
52   20181104    10                Alabama           29                    LSU            0             12.25          +14                    LSU                Alabama      29      0.0     1.0
53   20181104    10               Oklahoma           51             Texas Tech           46             14.40        +10.5               Oklahoma               Oklahoma       5      0.0     1.0
54   20181104    10               Stanford           23             Washington           27             -6.54         -9.5               Stanford             Washington      -4      1.0     1.0
55   20181104    10                    USC           38           Oregon State           21             25.67          +14                    USC                    USC      17      1.0     1.0
56   20181104    10                    BYU           16            Boise State           21            -10.41        -14.5                    BYU            Boise State      -5      1.0     1.0
57   20181104    10        San Diego State           31             New Mexico           23             11.86          +11                   None        San Diego State       8      NaN     1.0
58   20181104    10           Fresno State           48                   UNLV            3             28.87        +24.5           Fresno State           Fresno State      45      1.0     1.0
59   20181104    10             California           13       Washington State           19            -17.82          -11       Washington State       Washington State      -6      0.0     1.0
60   20181104    10             Utah State           56                Hawai'i           17             21.83          +17             Utah State             Utah State      39      1.0     1.0

[390 rows x 13 columns]

In [7]:
print("ATS:")
print(ats_wins, "/", str(ats_losses + ats_wins))
print(ats_wins / (ats_losses + ats_wins))
print()

print("SU:")
print(su_wins, "/", str(su_losses + su_wins))
print(su_wins / (su_losses + su_wins))

ATS:
176 / 337
0.5222551928783383

SU:
276 / 390
0.7076923076923077