In [1]:
import pandas as pd

df = pd.read_csv("Data/teams_aPPD.tsv", sep="\t", index_col="team")
df = df[["aOPPD", "aDPPD", "net_aPPD"]].copy().sort_values(by="net_aPPD", ascending=False).round(2)
df

                   aOPPD  aDPPD  net_aPPD
team
Alabama             1.65  -1.44      3.09
Georgia             1.52  -1.32      2.84
Clemson             0.84  -1.35      2.19
Michigan            0.92  -1.27      2.18
Mississippi State   0.99  -1.19      2.18
Florida             0.72  -1.40      2.12
Kentucky            0.42  -1.59      2.01
LSU                 1.05  -0.92      1.97
Oklahoma            1.94   0.02      1.92
Ohio State          1.36  -0.49      1.85
Iowa                0.85  -0.99      1.84
Penn State          0.89  -0.80      1.69
Texas A&M           0.93  -0.72      1.65
West Virginia       0.96  -0.59      1.55
Army                1.23  -0.32      1.55
South Carolina      0.69  -0.76      1.45
Washington          0.79  -0.56      1.35
Notre Dame          0.49  -0.85      1.34
NC State            0.84  -0.48      1.32
Iowa State          0.46  -0.80      1.27
Missouri            0.68  -0.57      1.25
Appalachian State   0.55  -0.63      1.17
Texas               0.70  -0.44      1.13
Utah State          0.98  -0.11      1.09
Auburn             -0.16  -1.19      1.04
Utah                0.07  -0.94      1.01
Michigan State     -0.03  -1.02      0.98
UCF                 1.12   0.15      0.97
Washington State    1.31   0.34      0.97
Miami              -0.20  -1.13      0.93
...                  ...    ...       ...
Florida Atlantic   -0.35   0.71     -1.05
UNLV               -0.31   0.74     -1.05
Navy               -0.45   0.64     -1.09
Nevada             -1.17  -0.07     -1.10
East Carolina      -1.07   0.19     -1.26
SMU                -0.60   0.69     -1.29
Middle Tennessee   -0.65   0.67     -1.31
Louisville         -0.53   0.78     -1.32
Illinois           -0.37   0.97     -1.34
Georgia State      -0.47   0.94     -1.40
California         -1.78  -0.31     -1.47
Rutgers            -1.12   0.39     -1.51
Coastal Carolina    0.22   1.75     -1.53
Louisiana           0.40   1.94     -1.54
San Jos√© State     -1.65  -0.09     -1.56
Western Kentucky   -1.18   0.41     -1.59
South Alabama      -0.62   0.98     -1.61
UTEP               -0.68   0.94     -1.63
Bowling Green      -0.63   1.05     -1.68
Old Dominion       -0.26   1.43     -1.70
North Carolina     -0.61   1.20     -1.81
Kent State         -0.91   0.92     -1.83
UT San Antonio     -1.28   0.56     -1.85
Charlotte          -0.88   1.01     -1.89
Louisiana Monroe   -0.87   1.04     -1.91
UMass              -0.44   1.56     -2.00
Oregon State       -0.23   1.90     -2.14
Texas State        -1.84   0.35     -2.19
Rice               -1.55   0.99     -2.54
Connecticut        -0.81   2.51     -3.31

[129 rows x 3 columns]

In [4]:
#outfile = open("aPPD_asTable.txt", "w")

#for index, row in df.iterrows():
#    outfile.write(index + " | " + str(row["aOPPD"]) + " | " + str(row["aDPPD"]) + " | " + str(row["net_aPPD"]) + "\n")
df.to_csv("aPPD_asTable.txt", sep="|")