In [1]:
SEASON = 2017

START_BETTING = 4
END_BETTING = 15

BET_THRESHOLD = 0.1
HFA = 3.0

In [2]:
import pandas as pd

pd.set_option('display.max_columns', 500)  # prints the df properly in console instead of splitting up columns
pd.set_option('display.width', 1000)

df = pd.read_json("https://api.collegefootballdata.com/games?year=" + str(SEASON))
df = df[(df.away_conference.notnull()) & (df.home_conference.notnull())]
df = df[["id", "start_date", "week", "away_team", "away_points", "home_team", "home_points"]]
df = df.set_index("id")
df.index = df.index.rename("game_id")
df

                         start_date  week              away_team  away_points              home_team  home_points
game_id
400935282  2017-08-26T14:30:00.000Z     1           Oregon State           27         Colorado State           58
400938887  2017-08-26T18:00:00.000Z     1                Hawai'i           38                  UMass           35
400941786  2017-08-26T19:30:00.000Z     1          South Florida           42         San Jos√© State           22
400935257  2017-08-26T22:00:00.000Z     1               Stanford           62                   Rice            7
400938591  2017-08-31T18:00:00.000Z     1  Florida International           17                    UCF           61
400935230  2017-08-31T19:00:00.000Z     1                Buffalo            7              Minnesota           17
400934493  2017-08-31T19:30:00.000Z     1                  Tulsa           24         Oklahoma State           59
400935229  2017-08-31T20:00:00.000Z     1             Ohio State           49                Indiana           21
400941789  2017-08-31T21:20:00.000Z     1       Louisiana Monroe           29                Memphis           37
400935247  2017-08-31T22:30:00.000Z     1       New Mexico State           31          Arizona State           37
400944891  2017-09-01T18:30:00.000Z     1              Charlotte            7       Eastern Michigan           24
400938592  2017-09-01T20:00:00.000Z     1                   Navy           42       Florida Atlantic           19
400935250  2017-09-01T20:00:00.000Z     1             Washington           30                Rutgers           14
400935249  2017-09-01T20:00:00.000Z     1         Colorado State            3               Colorado           17
400935231  2017-09-01T21:00:00.000Z     1             Utah State           10              Wisconsin           59
400937446  2017-09-01T21:30:00.000Z     1         Boston College           23      Northern Illinois           20
400937447  2017-09-02T12:00:00.000Z     1             Kent State            3                Clemson           56
400935237  2017-09-02T12:00:00.000Z     1                  Akron            0             Penn State           52
400935234  2017-09-02T12:00:00.000Z     1          Bowling Green           10         Michigan State           35
400935233  2017-09-02T12:00:00.000Z     1                Wyoming            3                   Iowa           24
400934495  2017-09-02T12:00:00.000Z     1               Maryland           51                  Texas           41
400935232  2017-09-02T12:00:00.000Z     1             Ball State           21               Illinois           24
400935256  2017-09-02T12:20:00.000Z     1             California           35         North Carolina           30
400933837  2017-09-02T15:00:00.000Z     1               NC State           28         South Carolina           35
400934573  2017-09-02T15:30:00.000Z     1                 Temple           16             Notre Dame           49
400935236  2017-09-02T15:30:00.000Z     1                 Nevada           20           Northwestern           31
400933830  2017-09-02T15:30:00.000Z     1               Michigan           33                Florida           17
400934492  2017-09-02T15:30:00.000Z     1                   UTEP            7               Oklahoma           56
400944830  2017-09-02T15:45:00.000Z     1                   Troy           13            Boise State           24
400933832  2017-09-02T16:00:00.000Z     1               Kentucky           24   Southern Mississippi           17
...                             ...   ...                    ...          ...                    ...          ...
400933938  2017-11-25T16:00:00.000Z    13             Vanderbilt           42              Tennessee           24
400941853  2017-11-25T16:00:00.000Z    13                 Temple           43                  Tulsa           22
400935328  2017-11-25T16:30:00.000Z    13                Arizona           30          Arizona State           42
400944881  2017-11-25T17:00:00.000Z    13       Georgia Southern           34              Louisiana           24
400945309  2017-11-25T17:00:00.000Z    13                Wyoming           17         San Jos√© State           20
400935327  2017-11-25T19:00:00.000Z    13           Oregon State           10                 Oregon           69
400933936  2017-11-25T19:30:00.000Z    13              Texas A&M           21                    LSU           45
400933937  2017-11-25T19:30:00.000Z    13                Clemson           34         South Carolina           10
400938669  2017-11-25T19:30:00.000Z    13         UT San Antonio            6         Louisiana Tech           20
400934583  2017-11-25T20:00:00.000Z    13             Notre Dame           20               Stanford           38
400935330  2017-11-25T20:00:00.000Z    13       Washington State           14             Washington           41
400945310  2017-11-25T21:00:00.000Z    13                    BYU           30                Hawai'i           20
400935329  2017-11-25T22:00:00.000Z    13               Colorado           13                   Utah           34
400945306  2017-11-25T22:15:00.000Z    13             Utah State           35              Air Force           38
400955149  2017-12-01T20:00:00.000Z    14               Stanford           28                    USC           31
400985387  2017-12-02T12:00:00.000Z    14                  UMass           45  Florida International           63
401000149  2017-12-02T12:00:00.000Z    14       Louisiana Monroe           10          Florida State           42
400955150  2017-12-02T12:00:00.000Z    14                  Akron           28                 Toledo           45
400955152  2017-12-02T12:00:00.000Z    14            North Texas           17       Florida Atlantic           41
400955151  2017-12-02T12:00:00.000Z    14                Memphis           55                    UCF           62
400955157  2017-12-02T12:30:00.000Z    14                    TCU           17               Oklahoma           41
400944886  2017-12-02T13:00:00.000Z    14       Georgia Southern           17       Coastal Carolina           28
400944884  2017-12-02T14:30:00.000Z    14              Louisiana           14      Appalachian State           63
400955153  2017-12-02T16:00:00.000Z    14                Georgia           28                 Auburn            7
400944888  2017-12-02T16:30:00.000Z    14          South Alabama           17       New Mexico State           22
400944885  2017-12-02T19:30:00.000Z    14                   Troy           32         Arkansas State           25
400955154  2017-12-02T19:45:00.000Z    14           Fresno State           14            Boise State           17
400955156  2017-12-02T20:00:00.000Z    14             Ohio State           27              Wisconsin           21
400955155  2017-12-02T20:00:00.000Z    14                  Miami            3                Clemson           38
400934572  2017-12-09T15:00:00.000Z    15                   Army           14                   Navy           13

[719 rows x 6 columns]

In [3]:
for index, row in df.iterrows():
    sd = row["start_date"]
    year = sd.split("-")[0]
    month = sd.split("-")[1]
    day = sd.split("-")[2][:2]
    
    df.at[index, "start_date"] = year+month+day
df

          start_date  week              away_team  away_points              home_team  home_points
game_id
400935282   20170826     1           Oregon State           27         Colorado State           58
400938887   20170826     1                Hawai'i           38                  UMass           35
400941786   20170826     1          South Florida           42         San Jos√© State           22
400935257   20170826     1               Stanford           62                   Rice            7
400938591   20170831     1  Florida International           17                    UCF           61
400935230   20170831     1                Buffalo            7              Minnesota           17
400934493   20170831     1                  Tulsa           24         Oklahoma State           59
400935229   20170831     1             Ohio State           49                Indiana           21
400941789   20170831     1       Louisiana Monroe           29                Memphis           37
400935247   20170831     1       New Mexico State           31          Arizona State           37
400944891   20170901     1              Charlotte            7       Eastern Michigan           24
400938592   20170901     1                   Navy           42       Florida Atlantic           19
400935250   20170901     1             Washington           30                Rutgers           14
400935249   20170901     1         Colorado State            3               Colorado           17
400935231   20170901     1             Utah State           10              Wisconsin           59
400937446   20170901     1         Boston College           23      Northern Illinois           20
400937447   20170902     1             Kent State            3                Clemson           56
400935237   20170902     1                  Akron            0             Penn State           52
400935234   20170902     1          Bowling Green           10         Michigan State           35
400935233   20170902     1                Wyoming            3                   Iowa           24
400934495   20170902     1               Maryland           51                  Texas           41
400935232   20170902     1             Ball State           21               Illinois           24
400935256   20170902     1             California           35         North Carolina           30
400933837   20170902     1               NC State           28         South Carolina           35
400934573   20170902     1                 Temple           16             Notre Dame           49
400935236   20170902     1                 Nevada           20           Northwestern           31
400933830   20170902     1               Michigan           33                Florida           17
400934492   20170902     1                   UTEP            7               Oklahoma           56
400944830   20170902     1                   Troy           13            Boise State           24
400933832   20170902     1               Kentucky           24   Southern Mississippi           17
...              ...   ...                    ...          ...                    ...          ...
400933938   20171125    13             Vanderbilt           42              Tennessee           24
400941853   20171125    13                 Temple           43                  Tulsa           22
400935328   20171125    13                Arizona           30          Arizona State           42
400944881   20171125    13       Georgia Southern           34              Louisiana           24
400945309   20171125    13                Wyoming           17         San Jos√© State           20
400935327   20171125    13           Oregon State           10                 Oregon           69
400933936   20171125    13              Texas A&M           21                    LSU           45
400933937   20171125    13                Clemson           34         South Carolina           10
400938669   20171125    13         UT San Antonio            6         Louisiana Tech           20
400934583   20171125    13             Notre Dame           20               Stanford           38
400935330   20171125    13       Washington State           14             Washington           41
400945310   20171125    13                    BYU           30                Hawai'i           20
400935329   20171125    13               Colorado           13                   Utah           34
400945306   20171125    13             Utah State           35              Air Force           38
400955149   20171201    14               Stanford           28                    USC           31
400985387   20171202    14                  UMass           45  Florida International           63
401000149   20171202    14       Louisiana Monroe           10          Florida State           42
400955150   20171202    14                  Akron           28                 Toledo           45
400955152   20171202    14            North Texas           17       Florida Atlantic           41
400955151   20171202    14                Memphis           55                    UCF           62
400955157   20171202    14                    TCU           17               Oklahoma           41
400944886   20171202    14       Georgia Southern           17       Coastal Carolina           28
400944884   20171202    14              Louisiana           14      Appalachian State           63
400955153   20171202    14                Georgia           28                 Auburn            7
400944888   20171202    14          South Alabama           17       New Mexico State           22
400944885   20171202    14                   Troy           32         Arkansas State           25
400955154   20171202    14           Fresno State           14            Boise State           17
400955156   20171202    14             Ohio State           27              Wisconsin           21
400955155   20171202    14                  Miami            3                Clemson           38
400934572   20171209    15                   Army           14                   Navy           13

[719 rows x 6 columns]

In [4]:
import lineData
from aPPD import predictGames
import numpy as np

def simulateWeek(week, betThreshold):
    week_df = df[df.week == week].copy()
    
    week_df["prediction_noHFA"] = predictGames((week_df.away_team, week_df.home_team), season=SEASON, weekThrough=week-1)
    week_df = week_df[week_df.prediction_noHFA != -999]
    week_df = week_df.round(2)
    
    days = week_df.start_date.unique()
    firstDay = int(days[0]) - 1
    lastDay = int(days[-1]) + 1
    
    lines_df = pd.DataFrame()
    for date in range(firstDay, lastDay+1):
        day = int(str(date)[-2:])
        if day <= 31 and day > 0:
            #print(date)
            lines_df = lines_df.append(lineData.getLines(str(date)), ignore_index=True)
        else:
            pass
    
    week_df = pd.merge(week_df, lines_df, how="left", on=["away_team", "home_team"])
    week_df = week_df[week_df.opening_line != "N/A"]
    
    week_df.loc[week_df.opening_line == "PK", "opening_line"] = 0
    
    week_df["bet_ats"] = None
    week_df["bet_su"] = None
    
    for index, row in week_df.iterrows():
        if row["prediction_noHFA"] - float(row["opening_line"]) >= (betThreshold + HFA):
            week_df.at[index, "bet_ats"] = row["away_team"]
        elif row["prediction_noHFA"] - float(row["opening_line"]) <= -1*betThreshold:
            week_df.at[index, "bet_ats"] = row["home_team"]
    
    for index, row in week_df.iterrows():
        if row["prediction_noHFA"] >= betThreshold:
            week_df.at[index, "bet_su"] = row["away_team"]
        elif row["prediction_noHFA"] <= -1*betThreshold:
            week_df.at[index, "bet_su"] = row["home_team"]
    
    week_df["result"] = week_df["away_points"] - week_df["home_points"]
    
    week_df["win_ats"] = np.nan
    week_df.loc[week_df.bet_ats.notnull(), "win_ats"] = 0
    week_df["win_su"] = np.nan
    week_df.loc[week_df.bet_su.notnull(), "win_su"] = 0
    
    for index, row in week_df.iterrows():
        if row["bet_ats"]:
            if str(row["result"]) == row["opening_line"]:  # push
                week_df.at[index, "win_ats"] = np.nan
            elif row["result"] > float(row["opening_line"]):  # road team wins
                if row["bet_ats"] == row["away_team"]:
                    week_df.at[index, "win_ats"] = 1
            elif row["result"] < float(row["opening_line"]):  # home team wins
                if row["bet_ats"] == row["home_team"]:
                    week_df.at[index, "win_ats"] = 1
    
    for index, row in week_df.iterrows():
        if row["bet_su"]:
            if row["result"] > 0:  # road team wins
                if row["bet_su"] == row["away_team"]:
                    week_df.at[index, "win_su"] = 1
            elif row["result"] < 0:  # home team wins
                if row["bet_su"] == row["home_team"]:
                    week_df.at[index, "win_su"] = 1
    
    metrics = {
        "ats_wins": len(week_df[week_df.win_ats == 1]),
        "ats_losses": len(week_df[week_df.win_ats == 0]),
        "ats_acc": np.nanmean(week_df.win_ats),
        
        "su_wins": len(week_df[week_df.win_su == 1]),
        "su_losses": len(week_df[week_df.win_su == 0]),
        "su_acc": np.nanmean(week_df.win_su)
    }
  
    return week_df, metrics

In [5]:
#week_df, metrics = simulateWeek(7, BET_THRESHOLD)
#print(metrics)

In [6]:
season_df = pd.DataFrame()

ats_wins = 0
ats_losses = 0
su_wins = 0
su_losses = 0
for w in range(START_BETTING, END_BETTING+1):
    print("WEEK %d:" % w)
    week_df, week_metrics = simulateWeek(w, BET_THRESHOLD)
    print(week_metrics)
    print()
    
    ats_wins += week_metrics["ats_wins"]
    ats_losses += week_metrics["ats_losses"]
    
    su_wins += week_metrics["su_wins"]
    su_losses += week_metrics["su_losses"]
    
    season_df = pd.concat([season_df, week_df], sort=False)

season_df

WEEK 4:
{'ats_wins': 22, 'ats_losses': 27, 'ats_acc': 0.4489795918367347, 'su_wins': 34, 'su_losses': 19, 'su_acc': 0.6415094339622641}

WEEK 5:
{'ats_wins': 24, 'ats_losses': 26, 'ats_acc': 0.48, 'su_wins': 38, 'su_losses': 14, 'su_acc': 0.7307692307692307}

WEEK 6:
{'ats_wins': 29, 'ats_losses': 24, 'ats_acc': 0.5471698113207547, 'su_wins': 40, 'su_losses': 16, 'su_acc': 0.7142857142857143}

WEEK 7:
{'ats_wins': 24, 'ats_losses': 23, 'ats_acc': 0.5106382978723404, 'su_wins': 36, 'su_losses': 23, 'su_acc': 0.6101694915254238}

WEEK 8:
{'ats_wins': 21, 'ats_losses': 24, 'ats_acc': 0.4666666666666667, 'su_wins': 39, 'su_losses': 15, 'su_acc': 0.7222222222222222}

WEEK 9:
{'ats_wins': 26, 'ats_losses': 17, 'ats_acc': 0.6046511627906976, 'su_wins': 35, 'su_losses': 19, 'su_acc': 0.6481481481481481}

WEEK 10:
{'ats_wins': 20, 'ats_losses': 22, 'ats_acc': 0.47619047619047616, 'su_wins': 39, 'su_losses': 21, 'su_acc': 0.65}

WEEK 11:
{'ats_wins': 27, 'ats_losses': 14, 'ats_acc': 0.6585365853658537, 'su_wins': 40, 'su_losses': 12, 'su_acc': 0.7692307692307693}

WEEK 12:
{'ats_wins': 19, 'ats_losses': 26, 'ats_acc': 0.4222222222222222, 'su_wins': 46, 'su_losses': 13, 'su_acc': 0.7796610169491526}

WEEK 13:
{'ats_wins': 27, 'ats_losses': 19, 'ats_acc': 0.5869565217391305, 'su_wins': 43, 'su_losses': 18, 'su_acc': 0.7049180327868853}

WEEK 14:
{'ats_wins': 9, 'ats_losses': 4, 'ats_acc': 0.6923076923076923, 'su_wins': 12, 'su_losses': 3, 'su_acc': 0.8}

WEEK 15:
{'ats_wins': 1, 'ats_losses': 0, 'ats_acc': 1.0, 'su_wins': 1, 'su_losses': 0, 'su_acc': 1.0}

   start_date  week         away_team  away_points              home_team  home_points  prediction_noHFA opening_line            bet_ats             bet_su  result  win_ats  win_su
0    20170921     4            Temple            7          South Florida           43            -17.28          -19               None      South Florida     -36      NaN     1.0
1    20170922     4          Virginia           42            Boise State           23            -17.76          -14        Boise State        Boise State      19      0.0     0.0
2    20170922     4              Utah           30                Arizona           24             -2.86         +4.5            Arizona            Arizona       6      0.0     0.0
3    20170923     4        Kent State            3             Louisville           42            -40.37        -39.5         Louisville         Louisville     -39      0.0     1.0
4    20170923     4     West Virginia           56                 Kansas           34             82.42        +20.5      West Virginia      West Virginia      22      1.0     1.0
5    20170923     4             UMass           13              Tennessee           17            -39.57        -26.5          Tennessee          Tennessee      -4      0.0     1.0
6    20170923     4         Texas A&M           50               Arkansas           43             19.60          NaN               None          Texas A&M       7      NaN     1.0
7    20170923     4              Army           17                 Tulane           21              5.66           -2               Army               Army      -4      0.0     0.0
8    20170923     4        Texas Tech           27                Houston           24             17.76         -6.5         Texas Tech         Texas Tech       3      1.0     1.0
9    20170923     4          NC State           27          Florida State           21             -8.64        -12.5           NC State      Florida State       6      1.0     0.0
10   20170923     4        Pittsburgh           17           Georgia Tech           35            -24.62         -7.5       Georgia Tech       Georgia Tech     -18      1.0     1.0
11   20170923     4        New Mexico           16                  Tulsa           13              6.62        -12.5         New Mexico         New Mexico       3      1.0     1.0
12   20170923     4              Ohio           27       Eastern Michigan           20            -38.52         -2.5   Eastern Michigan   Eastern Michigan       7      0.0     0.0
13   20170923     4      Old Dominion            0          Virginia Tech           38            -43.12        -24.5      Virginia Tech      Virginia Tech     -38      1.0     1.0
14   20170923     4               UCF           38               Maryland           10            -29.87         -3.5           Maryland           Maryland      28      0.0     0.0
15   20170923     4              Duke           27         North Carolina           17             48.24         +2.5               Duke               Duke      10      1.0     1.0
16   20170923     4           Rutgers           17               Nebraska           27            -10.14          -11               None           Nebraska     -10      NaN     1.0
17   20170923     4    Louisiana Tech           16         South Carolina           17            -15.73        -10.5     South Carolina     South Carolina      -1      0.0     1.0
18   20170923     4           Alabama           59             Vanderbilt            0              3.60        +19.5         Vanderbilt            Alabama      59      0.0     1.0
19   20170923     4               TCU           44         Oklahoma State           31            -33.22        -11.5     Oklahoma State     Oklahoma State      13      0.0     0.0
20   20170923     4               USC           30             California           20             19.62        +15.5                USC                USC      10      0.0     1.0
21   20170923     4        Miami (OH)           31       Central Michigan           14             47.17           +1         Miami (OH)         Miami (OH)      17      1.0     1.0
22   20170923     4        Cincinnati           32                   Navy           42            -35.96        -10.5               Navy               Navy     -10      0.0     1.0
23   20170923     4    Boston College            7                Clemson           34            -45.73          -32            Clemson            Clemson     -27      0.0     1.0
24   20170923     4  Georgia Southern           17                Indiana           52             -1.85        -22.5   Georgia Southern            Indiana     -35      0.0     1.0
25   20170923     4       Wake Forest           20      Appalachian State           19             17.47         +3.5        Wake Forest        Wake Forest       1      0.0     1.0
26   20170923     4          Michigan           28                 Purdue           10              9.81        +10.5             Purdue           Michigan      18      0.0     1.0
27   20170923     4  Louisiana Monroe           56              Louisiana           50             48.86           -5   Louisiana Monroe   Louisiana Monroe       6      1.0     1.0
28   20170923     4            Nevada            7       Washington State           45             -9.18        -25.5             Nevada   Washington State     -38      0.0     1.0
29   20170923     4             Akron           17                   Troy           22            -50.26        -14.5               Troy               Troy      -5      0.0     1.0
..        ...   ...               ...          ...                    ...          ...               ...          ...                ...                ...     ...      ...     ...
47   20171125    13        Vanderbilt           42              Tennessee           24             -3.78           -1          Tennessee          Tennessee      18      0.0     0.0
48   20171125    13            Temple           43                  Tulsa           22              6.43           +2             Temple             Temple      21      1.0     1.0
49   20171125    13           Arizona           30          Arizona State           42             -0.25            0      Arizona State      Arizona State     -12      1.0     1.0
50   20171125    13  Georgia Southern           34              Louisiana           24              6.25           -6   Georgia Southern   Georgia Southern      10      1.0     1.0
51   20171125    13           Wyoming           17         San Jos√© State           20             29.22          +22            Wyoming            Wyoming      -3      0.0     0.0
52   20171125    13      Oregon State           10                 Oregon           69            -21.47        -23.5               None             Oregon     -59      NaN     1.0
53   20171125    13         Texas A&M           21                    LSU           45             -1.71          -10          Texas A&M                LSU     -24      0.0     1.0
54   20171125    13           Clemson           34         South Carolina           10             20.18          +14            Clemson            Clemson      24      1.0     1.0
55   20171125    13    UT San Antonio            6         Louisiana Tech           20             -1.31           -1     Louisiana Tech     Louisiana Tech     -14      1.0     1.0
56   20171125    13        Notre Dame           20               Stanford           38             14.95         +1.5         Notre Dame         Notre Dame     -18      0.0     0.0
57   20171125    13  Washington State           14             Washington           41             -6.66          -10   Washington State         Washington     -27      0.0     1.0
58   20171125    13               BYU           30                Hawai'i           20              5.59         +3.5               None                BYU      10      NaN     1.0
59   20171125    13          Colorado           13                   Utah           34             -4.92        -10.5           Colorado               Utah     -21      0.0     1.0
60   20171125    13        Utah State           35              Air Force           38              0.96           -2               None         Utah State      -3      NaN     0.0
0    20171201    14          Stanford           28                    USC           31             -0.78           -3               None                USC      -3      NaN     1.0
1    20171202    14             UMass           45  Florida International           63              7.47         -1.5              UMass              UMass     -18      0.0     0.0
2    20171202    14  Louisiana Monroe           10          Florida State           42            -28.76        -27.5      Florida State      Florida State     -32      1.0     1.0
3    20171202    14             Akron           28                 Toledo           45            -10.52        -17.5              Akron             Toledo     -17      1.0     1.0
4    20171202    14       North Texas           17       Florida Atlantic           41             -9.17        -11.5               None   Florida Atlantic     -24      NaN     1.0
5    20171202    14           Memphis           55                    UCF           62             -4.38         -7.5            Memphis                UCF      -7      1.0     1.0
6    20171202    14               TCU           17               Oklahoma           41             -7.22         -5.5           Oklahoma           Oklahoma     -24      1.0     1.0
7    20171202    14  Georgia Southern           17       Coastal Carolina           28              4.21            0   Georgia Southern   Georgia Southern     -11      0.0     0.0
8    20171202    14         Louisiana           14      Appalachian State           63            -15.56        -14.5  Appalachian State  Appalachian State     -49      1.0     1.0
9    20171202    14           Georgia           28                 Auburn            7              1.24         -2.5            Georgia            Georgia      21      1.0     1.0
10   20171202    14     South Alabama           17       New Mexico State           22             -9.18           -8   New Mexico State   New Mexico State      -5      0.0     1.0
11   20171202    14              Troy           32         Arkansas State           25              3.57           -1               Troy               Troy       7      1.0     1.0
12   20171202    14      Fresno State           14            Boise State           17             -3.88          -10       Fresno State        Boise State      -3      1.0     1.0
13   20171202    14        Ohio State           27              Wisconsin           21             -1.13           +6          Wisconsin          Wisconsin       6      0.0     0.0
14   20171202    14             Miami            3                Clemson           38             -9.02         -7.5            Clemson            Clemson     -35      1.0     1.0
0    20171209    15              Army           14                   Navy           13              2.32         -3.5               Army               Army       1      1.0     1.0

[579 rows x 13 columns]

In [7]:
print("ATS:")
print(ats_wins, "/", str(ats_losses + ats_wins))
print(ats_wins / (ats_losses + ats_wins))
print()

print("SU:")
print(su_wins, "/", str(su_losses + su_wins))
print(su_wins / (su_losses + su_wins))

ATS:
249 / 475
0.5242105263157895

SU:
403 / 576
0.6996527777777778